# Historical Data — Schema Discovery

Discovers schema across DB1 (old production) and DB2 (production) for three domains:

1. **Sales** — sold items, carts/transactions, payment
2. **Orders & Manifests** — purchase orders, manifest headers/rows, CSV templates
3. **Inventory** — items, products, categories, product attributes

**Use cases:**
- 2025–2026 sales reporting
- Manifest header → standardized template mapping
- Category taxonomy + pricing intelligence for future order bids

**Run all cells, save, then share back for final export SQL.**

In [1]:
import os
import sys
from pathlib import Path
from urllib.parse import quote_plus

import pandas as pd
from sqlalchemy import create_engine, inspect, text

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 120)
pd.set_option("display.width", 200)


def _resolve_notebook_root() -> Path:
    """Find workspace/notebooks (parent of _shared/) from cwd or NOTEBOOK_DIR."""
    cwd = Path.cwd().resolve()
    if os.environ.get("NOTEBOOK_DIR"):
        p = Path(os.environ["NOTEBOOK_DIR"]).resolve()
        if (p / "_shared" / "config.example.py").is_file():
            return p
        if p.name == "_shared" and (p / "config.example.py").is_file():
            return p.parent
    for base in (cwd, *cwd.parents):
        for candidate in (base, base / "workspace" / "notebooks"):
            if (candidate / "_shared" / "config.example.py").is_file():
                return candidate
    raise FileNotFoundError(
        "Could not find workspace/notebooks/_shared/config.example.py; "
        "set NOTEBOOK_DIR to workspace/notebooks or run from repo root."
    )


NOTEBOOK_ROOT = _resolve_notebook_root()
SHARED_DIR = NOTEBOOK_ROOT / "_shared"
if str(SHARED_DIR) not in sys.path:
    sys.path.insert(0, str(SHARED_DIR))

_cfg = SHARED_DIR / "config_local.py"
if not _cfg.is_file():
    raise FileNotFoundError(
        f"Missing {_cfg} — copy _shared/config.example.py to _shared/config_local.py (see _shared/README.md)."
    )

from config_local import CONNECTIONS  # noqa: E402

OUTPUT_DIR = Path.cwd().resolve() if (Path.cwd().resolve() / "schema_discovery.ipynb").exists() else NOTEBOOK_ROOT / "historical-data"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


def make_engine(cfg: dict):
    user = quote_plus(str(cfg["user"]))
    pw = quote_plus(str(cfg["password"]))
    host = cfg["host"]
    port = int(cfg["port"])
    db = cfg["database"]
    return create_engine(f"postgresql+psycopg2://{user}:{pw}@{host}:{port}/{db}", future=True)


def open_connection(key: str):
    cfg = CONNECTIONS[key]
    eng = make_engine(cfg)
    schema = str(cfg.get("schema") or "public")
    label = cfg.get("label", key)
    return eng, schema, label


def describe_table(engine, table_name, schema="public"):
    sql = text(
        "SELECT column_name, data_type, is_nullable, column_default "
        "FROM information_schema.columns "
        "WHERE table_schema = :schema AND table_name = :tbl "
        "ORDER BY ordinal_position"
    )
    with engine.connect() as conn:
        return pd.read_sql_query(sql, conn, params={"schema": schema, "tbl": table_name})


def sample_table(engine, table_name, schema="public", limit=5):
    sql = text(f'SELECT * FROM "{schema}"."{table_name}" LIMIT :lim')
    with engine.connect() as conn:
        return pd.read_sql_query(sql, conn, params={"lim": limit})


def row_count(engine, table_name, schema="public"):
    sql = text(f'SELECT COUNT(*) AS n FROM "{schema}"."{table_name}"')
    with engine.connect() as conn:
        return conn.execute(sql).scalar()


def table_exists(engine, table_name, schema="public"):
    return table_name in inspect(engine).get_table_names(schema=schema)


def get_fks(engine, table_name, schema="public"):
    sql = text("""
        SELECT kcu.column_name, ccu.table_name AS fk_table, ccu.column_name AS fk_column
        FROM information_schema.table_constraints tc
        JOIN information_schema.key_column_usage kcu ON tc.constraint_name = kcu.constraint_name
        JOIN information_schema.constraint_column_usage ccu ON ccu.constraint_name = tc.constraint_name
        WHERE tc.table_schema = :schema AND tc.table_name = :tbl AND tc.constraint_type = 'FOREIGN KEY'
    """)
    with engine.connect() as conn:
        return pd.read_sql_query(sql, conn, params={"schema": schema, "tbl": table_name})


def full_describe(engine, table_name, schema="public", sample_n=5, show_fks=True):
    """One-shot: columns, row count, FKs, sample rows."""
    n = row_count(engine, table_name, schema)
    cols_df = describe_table(engine, table_name, schema)
    print(f"\n{'='*70}")
    print(f"  {table_name}  ({n:,} rows)")
    print(f"{'='*70}")
    print("\nColumns:")
    display(cols_df)
    if show_fks:
        fks = get_fks(engine, table_name, schema)
        if len(fks):
            print("\nForeign keys:")
            display(fks)
    if n > 0 and sample_n > 0:
        print(f"\nSample ({min(sample_n, n)} rows):")
        display(sample_table(engine, table_name, schema, sample_n))
    return cols_df, n


print("Notebook root:", NOTEBOOK_ROOT)
print("Shared dir:", SHARED_DIR)
print("Output dir:", OUTPUT_DIR)
print("Available DB keys:", list(CONNECTIONS.keys()))

Notebook dir: E:\ecothrift-dashboard\workspace\notebooks
Output dir: E:\ecothrift-dashboard\workspace\notebooks\historical-data
Available DB keys: ['old_production', 'production', 'dev']

---
# PART 1 — DB2 (Production)
2nd-generation app. Currently live. Tables prefixed `inventory_`, `pos_`, etc.

In [2]:
eng2, sch2, lab2 = open_connection("production")
print(f"Connected: {lab2}")

all_db2 = sorted(inspect(eng2).get_table_names(schema=sch2))
print(f"\nAll tables ({len(all_db2)}):")
for t in all_db2:
    print(f"  {t}")

Connected: DB2 — Production (local restore / Heroku name may differ)

All tables (84):
  auth_group
  auth_group_permissions
  auth_permission
  core_address
  core_business_event
  core_contact
  core_customer_profile
  core_employee_profile
  core_event_category
  core_manifest
  core_s3_file
  core_user
  core_user_groups
  core_user_user_permissions
  core_work_location
  django_admin_log
  django_cache_table
  django_content_type
  django_migrations
  django_session
  hr_availability
  hr_blackout_date
  hr_budget
  hr_clock_event
  hr_compensation
  hr_department
  hr_holiday
  hr_holiday_departments
  hr_onboarding_checklist
  hr_pay_grade
  hr_pay_period
  hr_permission_audit_log
  hr_permission_profile
  hr_pto_accrual
  hr_pto_balance
  hr_pto_policy
  hr_pto_request
  hr_schedule
  hr_shift
  hr_time_audit_log
  hr_time_break
  hr_time_entry
  hr_time_modification_request
  hr_time_notification
  hr_time_notification_preference
  inventory_csv_field_mapping
  inventory_csv_template
  inventory_customer_message
  inventory_item
  inventory_item_history
  inventory_item_scan_history
  inventory_location
  inventory_manifest_rows
  inventory_preprocessing_detail
  inventory_pricing_template
  inventory_processing_detail
  inventory_product
  inventory_product_class
  inventory_purchase_order
  inventory_raw_manifest
  inventory_standardization_run
  inventory_store_configuration
  inventory_vendor
  migrated_items
  pos_bank_transaction
  pos_cart
  pos_cart_line
  pos_cash_deposit
  pos_cash_management_settings
  pos_change_request
  pos_discount_rule
  pos_drawer
  pos_drawer_shift
  pos_payment
  pos_receipt
  pos_receipt_template
  pos_register
  pos_revenue_goal
  pos_supplemental_drawer
  pos_supplemental_drawer_transaction
  pos_transaction_void
  temp_old_items
  token_blacklist_blacklistedtoken
  token_blacklist_outstandingtoken

## 1A — DB2 Inventory tables

In [3]:
db2_inv_tables = [t for t in all_db2 if t.startswith("inventory_")]
print("Inventory tables:", db2_inv_tables)

db2_schemas = {}
for t in db2_inv_tables:
    cols_df, n = full_describe(eng2, t, sch2, sample_n=3)
    db2_schemas[t] = {"cols": set(cols_df["column_name"]), "n": n}

Inventory tables: ['inventory_csv_field_mapping', 'inventory_csv_template', 'inventory_customer_message', 'inventory_item', 'inventory_item_history', 'inventory_item_scan_history', 'inventory_location', 'inventory_manifest_rows', 'inventory_preprocessing_detail', 'inventory_pricing_template', 'inventory_processing_detail', 'inventory_product', 'inventory_product_class', 'inventory_purchase_order', 'inventory_raw_manifest', 'inventory_standardization_run', 'inventory_store_configuration', 'inventory_vendor']

======================================================================
  inventory_csv_field_mapping  (120 rows)
======================================================================

Columns:

            column_name          data_type is_nullable column_default
0                    id             bigint          NO           None
1         source_column  character varying          NO           None
2          target_field  character varying          NO           None
3  transform_expression               text          NO           None
4         default_value  character varying          NO           None
5           is_required            boolean          NO           None
6                 order            integer          NO           None
7           template_id             bigint          NO           None

Foreign keys:

   column_name                fk_table fk_column
0  template_id  inventory_csv_template        id

Sample (3 rows):

   id     source_column  target_field transform_expression default_value  is_required  order  template_id
0   1  Item Description   description   str(value).strip()                       True      0            1
1   2               Qty      quantity           int(value)             1         True      0            1
2   3       Unit Retail  retail_value         float(value)                       True      0            1

======================================================================
  inventory_csv_template  (10 rows)
======================================================================

Columns:

            column_name                 data_type is_nullable column_default
0                    id                    bigint          NO           None
1                  name         character varying          NO           None
2      header_signature                      text          NO           None
3             is_active                   boolean          NO           None
4  confidence_threshold                   integer          NO           None
5            created_at  timestamp with time zone          NO           None
6            updated_at  timestamp with time zone          NO           None
7         created_by_id                    bigint         YES           None
8         updated_by_id                    bigint         YES           None
9             vendor_id                    bigint         YES           None

Foreign keys:

     column_name          fk_table fk_column
0      vendor_id  inventory_vendor        id
1  created_by_id         core_user        id
2  updated_by_id         core_user        id

Sample (3 rows):

,id,name,header_signature,is_active,confidence_threshold,created_at,updated_at,created_by_id,updated_by_id,vendor_id
0,1,"Walmart Template - Model, Category, UPC, Item#, PalletID, Dept",UPC|Item #|Model #|Item Description|Category|Department|Qty|Unit Retail|Ext. Retail|Unit Weight|Pallet ID|Inventory ...,True,90,2025-08-18 17:58:00.199623+00:00,2025-08-18 17:58:00.199639+00:00,1,None,1
1,2,Unknown Template - 8/22/2025,location|unit_retail|qty|ext_retail|upc|item|item_description|category|||,True,90,2025-08-22 18:35:37.090509+00:00,2025-08-22 18:35:37.090528+00:00,3,None,1
2,3,"Target - Category, Subcategory, UPC, ITEM #, TCIN, PalletID, Condition",Pallet ID|Item #|Product Class|Category Code|Seller Category|Item Description|Qty|Unit Retail|Ext. Retail|Origin|UPC...,True,90,2025-08-25 14:52:14.742053+00:00,2025-08-25 14:52:14.742069+00:00,1,None,2

======================================================================
  inventory_customer_message  (3 rows)
======================================================================

Columns:

  column_name                 data_type is_nullable column_default
0          id                    bigint          NO           None
1     message         character varying          NO           None
2   is_active                   boolean          NO           None
3    priority                   integer          NO           None
4  start_date  timestamp with time zone         YES           None
5    end_date  timestamp with time zone         YES           None
6   click_url         character varying          NO           None
7  created_at  timestamp with time zone          NO           None
8  updated_at  timestamp with time zone          NO           None

Sample (3 rows):

,id,message,is_active,priority,start_date,end_date,click_url,created_at,updated_at
0,42,Coming in February: Consignment! We're starting with a select few. Interested? Let us know!,True,0,None,None,,2026-01-21 16:13:55.441369+00:00,2026-01-21 16:14:51.314936+00:00
1,40,Welcome Back! Canfield Eco-Thrift is NOW OPEN. We're thrilled to see you again!,True,10,None,None,,2026-01-21 16:13:15.469000+00:00,2026-01-21 16:15:02.795238+00:00
2,41,We hear you! We're working on a new label strategy so you won't need to use the price app.,True,5,None,None,,2026-01-21 16:13:49.457646+00:00,2026-01-21 16:15:22.906476+00:00

======================================================================
  inventory_item  (59,833 rows)
======================================================================

Columns:

                    column_name                 data_type is_nullable column_default
0                            id                    bigint          NO           None
1                           sku         character varying          NO           None
2                 serial_number         character varying         YES           None
3                       bulk_id         character varying         YES           None
4                 bulk_quantity                   integer         YES           None
5                  pricing_type         character varying          NO           None
6                starting_price                   numeric          NO           None
7                    retail_amt                   numeric         YES           None
8                        disc_a                   numeric         YES           None
9                        disc_b                   numeric         YES           None
10                  on_shelf_at                      date         YES           None
11      processing_completed_at  timestamp with time zone         YES           None
12                      sold_at  timestamp with time zone         YES           None
13                     sold_for                   numeric         YES           None
14                   created_at  timestamp with time zone          NO           None
15                   updated_at  timestamp with time zone          NO           None
16              manifest_row_id                    bigint         YES           None
17                   product_id                    bigint         YES           None
18             product_class_id                    bigint         YES           None
19  inventory_purchase_order_id                    bigint         YES           None
20              last_printed_at  timestamp with time zone         YES           None
21              sku_print_count                   integer          NO           None

Foreign keys:

                   column_name                  fk_table fk_column
0  inventory_purchase_order_id  inventory_purchase_order        id
1              manifest_row_id   inventory_manifest_rows        id
2             product_class_id   inventory_product_class        id
3                   product_id         inventory_product        id

Sample (3 rows):

,id,sku,serial_number,bulk_id,bulk_quantity,pricing_type,starting_price,retail_amt,disc_a,disc_b,on_shelf_at,processing_completed_at,sold_at,sold_for,created_at,updated_at,manifest_row_id,product_id,product_class_id,inventory_purchase_order_id,last_printed_at,sku_print_count
0,61730,ITMZ7S6SAK,None,None,None,discounting,7.49,14.98,0.1500,0.015,2026-01-17,2025-12-15 09:48:29.549450-06:00,2026-01-19 12:25:12.123209-06:00,7.46,2025-12-15 09:48:26.129829-06:00,2026-01-19 12:25:12.128780-06:00,NaN,41452,None,172.0,2025-12-15 15:48:29.549450+00:00,1
1,10521,ITMVVUL8QG,None,None,None,discounting,15.29,17.99,0.0255,0.085,2026-01-20,None,None,NaN,2025-08-25 10:35:41.812502-05:00,2026-01-20 10:38:33.976601-06:00,3412.0,5026,None,4.0,NaT,0
2,6032,ITMF9Q5L6M,None,None,None,discounting,27.70,55.40,0.1500,0.015,2026-01-17,2025-08-20 16:49:36.008966-05:00,2025-08-23 10:46:54.666301-05:00,19.39,2025-08-20 16:49:36.008969-05:00,2025-08-23 10:46:54.670318-05:00,NaN,2162,None,NaN,NaT,0

======================================================================
  inventory_item_history  (54,250 rows)
======================================================================

Columns:

      column_name                 data_type is_nullable column_default
0              id                    bigint          NO           None
1       condition         character varying          NO           None
2        location         character varying          NO           None
3          status         character varying          NO           None
4           notes                      text          NO           None
5      updated_on  timestamp with time zone          NO           None
6         item_id                    bigint          NO           None
7   updated_by_id                    bigint         YES           None
8  destination_id                    bigint         YES           None
9  dispatch_to_id                    bigint         YES           None

Foreign keys:

      column_name            fk_table fk_column
0  destination_id  inventory_location        id
1  dispatch_to_id  inventory_location        id
2         item_id      inventory_item        id
3   updated_by_id           core_user        id

Sample (3 rows):

     id  condition    location    status notes                       updated_on  item_id  updated_by_id  destination_id  dispatch_to_id
0  1209  very_good  APLE-FLOOR  on_shelf       2025-08-20 16:14:42.218218+00:00     2606              3               8               8
1  1212  very_good  APLE-FLOOR  on_shelf       2025-08-20 16:15:04.060106+00:00     2609              3               8               8
2  1213  very_good  APLE-FLOOR  on_shelf       2025-08-20 16:15:13.624427+00:00     2610              3               8               8

======================================================================
  inventory_item_scan_history  (403,239 rows)
======================================================================

Columns:

   column_name                 data_type is_nullable column_default
0           id                    bigint          NO           None
1   scanned_at  timestamp with time zone          NO           None
2   ip_address                      inet          NO           None
3   user_agent                      text          NO           None
4  device_type         character varying          NO           None
5   session_id         character varying          NO           None
6      item_id                    bigint          NO           None

Foreign keys:

  column_name        fk_table fk_column
0     item_id  inventory_item        id

Sample (3 rows):

,id,scanned_at,ip_address,user_agent,device_type,session_id,item_id
0,1,2025-10-07 19:35:50.971056+00:00,172.226.81.2,"Mozilla/5.0 (iPhone; CPU iPhone OS 18_6_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.6 Mobil...",mobile,,20275
1,2,2025-10-07 19:35:51.011639+00:00,75.244.206.71,"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36 Edg/...",desktop,,21869
2,3,2025-10-07 19:36:00.187081+00:00,172.59.78.7,"Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Mobile Safari/537.36",mobile,,20236

======================================================================
  inventory_location  (11 rows)
======================================================================

Columns:

     column_name                 data_type is_nullable column_default
0             id                    bigint          NO           None
1           name         character varying          NO           None
2           code         character varying          NO           None
3  location_type         character varying          NO           None
4      is_active                   boolean          NO           None
5     created_at  timestamp with time zone          NO           None
6     updated_at  timestamp with time zone          NO           None
7      parent_id                    bigint         YES           None

Foreign keys:

  column_name            fk_table fk_column
0   parent_id  inventory_location        id

Sample (3 rows):

   id                    name       code location_type  is_active                       created_at                       updated_at parent_id
0   1  Restoration - Assembly  REST-ASSM   restoration       True 2025-08-19 21:14:23.896992+00:00 2025-08-19 21:14:23.897001+00:00      None
1   2   Restoration - General   REST-GEN   restoration       True 2025-08-19 21:14:23.906569+00:00 2025-08-19 21:14:23.906578+00:00      None
2   3        Restoration - AV    REST-AV   restoration       True 2025-08-19 21:14:23.909990+00:00 2025-08-19 21:14:23.909998+00:00      None

======================================================================
  inventory_manifest_rows  (36,330 rows)
======================================================================

Columns:

          column_name                 data_type is_nullable column_default
0                  id                    bigint          NO           None
1          row_number                   integer          NO           None
2            quantity                   integer          NO           None
3         description                      text          NO           None
4        retail_value                   numeric          NO           None
5               brand         character varying          NO           None
6               model         character varying          NO           None
7            category         character varying          NO           None
8         subcategory         character varying          NO           None
9                 upc         character varying          NO           None
10                sku         character varying          NO           None
11         vendor_sku         character varying          NO           None
12          pallet_id         character varying          NO           None
13             box_id         character varying          NO           None
14       search_terms                      text          NO           None
15         created_at  timestamp with time zone          NO           None
16         updated_at  timestamp with time zone          NO           None
17  purchase_order_id                    bigint          NO           None

Foreign keys:

         column_name                  fk_table fk_column
0  purchase_order_id  inventory_purchase_order        id

Sample (3 rows):

,id,row_number,quantity,description,retail_value,brand,model,category,subcategory,upc,sku,vendor_sku,pallet_id,box_id,search_terms,created_at,updated_at,purchase_order_id
0,320,1,25,Generic_GenMerch_$100orless,25.00,,Generic_GenMerch_$100orless,MIXED_LOTS,,7.7777E+11,,7777702-77777,23234313,,,2025-08-18 19:57:39.039992+00:00,2025-08-18 19:57:39.040007+00:00,2
1,321,2,22,Generic_GenMerch_$100orless,25.00,,Generic_GenMerch_$100orless,MIXED_LOTS,,7.7777E+11,,7777702-77777,23112849,,,2025-08-18 19:57:39.041468+00:00,2025-08-18 19:57:39.041479+00:00,2
2,322,3,3,Seville Classics UltraHD Heavy-Duty Lockable Wall Storage Cabinet with Stainless Steel Doors,119.99,,UHD20229B,STORAGE,,1764199229,,370803571-73668,23326872,,HOME IMPROVEMENT,2025-08-18 19:57:39.042421+00:00,2025-08-18 19:57:39.042429+00:00,2

======================================================================
  inventory_preprocessing_detail  (36,330 rows)
======================================================================

Columns:

                   column_name                 data_type is_nullable column_default
0                           id                    bigint          NO           None
1                   row_number                   integer          NO           None
2         manifest_description                      text          NO           None
3               manifest_brand         character varying         YES           None
4               manifest_model         character varying         YES           None
5        manifest_retail_value                   numeric         YES           None
6            manifest_quantity                   integer          NO           None
7        manifest_match_status         character varying         YES           None
8   suggested_manifest_matches                     jsonb         YES           None
9   selected_manifest_match_id                   integer         YES           None
10          ai_generated_title         character varying         YES           None
11          ai_generated_brand         character varying         YES           None
12          ai_generated_model         character varying         YES           None
13        ai_generation_status         character varying         YES           None
14        product_match_status         character varying         YES           None
15   suggested_product_matches                     jsonb         YES           None
16   selected_product_match_id                   integer         YES           None
17                pricing_type         character varying         YES           None
18              starting_price                   numeric         YES           None
19                     is_bulk                   boolean          NO           None
20               bulk_quantity                   integer          NO           None
21                      disc_a                   numeric         YES           None
22                      disc_b                   numeric         YES           None
23     pricing_dynamics_status         character varying         YES           None
24   item_rows_generated_count                   integer          NO           None
25       item_generated_status         character varying         YES           None
26                  created_at  timestamp with time zone          NO           None
27                  updated_at  timestamp with time zone          NO           None
28             manifest_row_id                    bigint          NO           None
29           purchase_order_id                    bigint          NO           None

Foreign keys:

         column_name                  fk_table fk_column
0    manifest_row_id   inventory_manifest_rows        id
1  purchase_order_id  inventory_purchase_order        id

Sample (3 rows):

,id,row_number,manifest_description,manifest_brand,manifest_model,manifest_retail_value,manifest_quantity,manifest_match_status,suggested_manifest_matches,selected_manifest_match_id,ai_generated_title,ai_generated_brand,ai_generated_model,ai_generation_status,product_match_status,suggested_product_matches,selected_product_match_id,pricing_type,starting_price,is_bulk,bulk_quantity,disc_a,disc_b,pricing_dynamics_status,item_rows_generated_count,item_generated_status,created_at,updated_at,manifest_row_id,purchase_order_id
0,823,185,Polyfill Comforter Poly Cotton Fabric Only Quality Fabrics Used White Color - Twin Size - 64x82,,,35.09,6,not_matched,[],None,Polyfill Comforter Poly Cotton White Twin Size 64x82,,,generated,not_matched,[],None,discounting,10.53,True,6,0.05,0.12,priced,1,generated,2025-08-22 18:34:18.107209+00:00,2025-08-25 14:27:56.371687+00:00,823,3
1,5226,2,"Honeywell Digital Ceramic Compact Tower Heater Black: Indoor Space Heater, Programmable Thermostat, 1500W, Electric",Honeywell,,21.49,22,not_matched,[],None,Honeywell Digital Ceramic Tower Heater Black 1500W Programmable Thermostat,Honeywell,,generated,not_matched,"[{'id': 6748, 'brand': 'Hefty', 'model': '', 'title': 'Hefty 13gal Odor Block Trash Can Black Touch-Top Rectangle', ...",None,discounting,18.27,False,1,0.04,0.12,priced,22,generated,2025-09-03 13:27:30.740858+00:00,2025-09-03 13:50:26.978468+00:00,5226,40
2,844,206,"CHEERMORE Women's Solid Color Velvet Boots, Slip On Warm Fluffy Platform Mid Calf Snow Boots, Winter Non-slip Soft &...",,,29.99,9,not_matched,[],None,CHEERMORE Women's Velvet Platform Mid Calf Snow Boots Size 9.5,CHEERMORE,Women's Solid Color Velvet Boots,generated,not_matched,[],None,discounting,9.00,True,9,0.05,0.12,priced,1,generated,2025-08-22 18:34:18.163147+00:00,2025-08-25 14:27:56.505001+00:00,844,3

======================================================================
  inventory_pricing_template  (4 rows)
======================================================================

Columns:

          column_name                 data_type is_nullable column_default
0                  id                    bigint          NO           None
1                name         character varying          NO           None
2  starting_price_pct                   numeric          NO           None
3              disc_a                   numeric         YES           None
4              disc_b                   numeric         YES           None
5          created_at  timestamp with time zone          NO           None
6          updated_at  timestamp with time zone          NO           None

Sample (3 rows):

   id         name  starting_price_pct  disc_a  disc_b                       created_at                       updated_at
0   2      Regular                80.0   0.050   0.120 2025-08-22 02:39:17.766533+00:00 2025-08-22 02:39:17.766533+00:00
1   3  High Demand                90.0   0.001   0.050 2025-08-22 02:39:17.767532+00:00 2025-08-22 02:39:17.767532+00:00
2   4    Essential                50.0   0.001   0.025 2025-08-22 02:39:17.767532+00:00 2025-08-22 02:39:17.767532+00:00

======================================================================
  inventory_processing_detail  (54,611 rows)
======================================================================

Columns:

                    column_name                 data_type is_nullable         column_default
0                            id                    bigint          NO                    NaN
1                       item_id                   integer          NO                    NaN
2               manifest_row_id                   integer         YES                    NaN
3             purchase_order_id                   integer         YES                    NaN
4               init_product_id                   integer         YES                    NaN
5            init_product_title         character varying          NO                    NaN
6            init_product_brand         character varying          NO                    NaN
7            init_product_model         character varying          NO                    NaN
8               init_price_type         character varying          NO                    NaN
9           init_price_starting                   numeric         YES                    NaN
10            init_price_disc_a                   numeric         YES                    NaN
11            init_price_disc_b                   numeric         YES                    NaN
12             init_item_retail                   numeric         YES                    NaN
13             final_product_id                   integer         YES                    NaN
14          final_product_title         character varying          NO                    NaN
15          final_product_brand         character varying          NO                    NaN
16          final_product_model         character varying          NO                    NaN
17             final_price_type         character varying          NO                    NaN
18         final_price_starting                   numeric         YES                    NaN
19           final_price_disc_a                   numeric         YES                    NaN
20           final_price_disc_b                   numeric         YES                    NaN
21            final_item_retail                   numeric         YES                    NaN
22          manifest_row_number                   integer         YES                    NaN
23         manifest_description                      text          NO                    NaN
24               manifest_brand         character varying          NO                    NaN
25               manifest_model         character varying          NO                    NaN
26        manifest_expected_qty                   integer         YES                    NaN
27        manifest_retail_value                   numeric         YES                    NaN
28                bulk_quantity                   integer         YES                    NaN
29                       status         character varying         YES                    NaN
30               product_status         character varying         YES                    NaN
31               pricing_status         character varying         YES                    NaN
32               history_status         character varying         YES                    NaN
33       item_history_condition         character varying         YES                    NaN
34     item_history_location_id                   integer         YES                    NaN
35           item_history_notes                      text         YES                    NaN
36  item_history_destination_id                   integer         YES                    NaN
37  item_history_dispatch_to_id                   integer         YES                    NaN
38                print_counter                   integer          NO                    NaN
39                 processed_at  timestamp with time zone         YES                    NaN
40              processed_by_id                   integer         YES                    NaN
41                 search_terms                      text          NO                    NaN
42         product_po_items_cnt                   integer         YES                    NaN
43            product_items_cnt                   integer         YES                    NaN
44                   created_at  timestamp with time zone          NO                    NaN
45                   updated_at  timestamp with time zone          NO                    NaN
46                     item_sku         character varying         YES  ''::character varying
47                serial_number         character varying         YES                    NaN
48                retail_status         character varying         YES                    NaN
49              item_history_id                   integer         YES                    NaN
50      item_history_updated_at  timestamp with time zone         YES                    NaN
51      item_history_updated_by         character varying         YES                    NaN
52        manifest_search_terms                      text          NO                    NaN
53         product_search_terms                      text          NO                    NaN

Sample (3 rows):

,id,item_id,manifest_row_id,purchase_order_id,init_product_id,init_product_title,init_product_brand,init_product_model,init_price_type,init_price_starting,init_price_disc_a,init_price_disc_b,init_item_retail,final_product_id,final_product_title,final_product_brand,final_product_model,final_price_type,final_price_starting,final_price_disc_a,final_price_disc_b,final_item_retail,manifest_row_number,manifest_description,manifest_brand,manifest_model,manifest_expected_qty,manifest_retail_value,bulk_quantity,status,product_status,pricing_status,history_status,item_history_condition,item_history_location_id,item_history_notes,item_history_destination_id,item_history_dispatch_to_id,print_counter,processed_at,processed_by_id,search_terms,product_po_items_cnt,product_items_cnt,created_at,updated_at,item_sku,serial_number,retail_status,item_history_id,item_history_updated_at,item_history_updated_by,manifest_search_terms,product_search_terms
0,1813,7747,1580,4,3194,Funko POP! Comic Cover Marvel X-Men 4 Magneto Figure,Funko,,discounting,16.99,0.0255,0.085,19.99,3194,Funko POP! Comic Cover Marvel X-Men 4 Magneto Figure,Funko,,discounting,16.99,0.0255,0.085,19.99,96,Funko POP! Comic Cover: Marvel- X-Men 4 Magneto Figure,Funko,,6,19.99,None,processed,approved,approved,created,good,None,,8,6,1,2025-08-27 16:41:41.591638+00:00,3,funko pop! comic cover: marvel- x-men 4 magneto figure funko toys funko - other 889698767002 lphj739530 89140322 ptb...,6,6,2025-08-25 15:41:47.600942+00:00,2025-08-27 16:41:41.593477+00:00,ITMV2QWA9D,889698767002,approved,7007,2025-08-27 16:22:08.073637+00:00,Retag User,funko pop! comic cover: marvel- x-men 4 magneto figure funko toys funko - other 889698767002 lphj739530 89140322 ptb...,funko pop! comic cover marvel x-men 4 magneto figure funko itmv2qwa9d 889698767002
1,2935,8870,2025,4,3639,Rubik's 3x3 Speed Cube,Rubik's,,discounting,12.74,0.0255,0.085,14.99,3639,Rubik's 3x3 Speed Cube,Rubik's,,discounting,12.74,0.0255,0.085,14.99,541,Rubik's 3x3 Speed Cube,Spin Master Games; Rubik's,,3,14.99,None,processed,approved,approved,created,good,None,,8,6,1,2025-08-28 17:29:10.621447+00:00,14,rubik's 3x3 speed cube spin master games; rubik's toys brain games 681147035775 lphj723052 90011779 ptba33823 new ru...,3,3,2025-08-25 15:41:47.600942+00:00,2025-08-28 17:29:10.622666+00:00,ITMYF3MEHV,681147035775,approved,8335,2025-08-28 17:29:08.953611+00:00,Russell Ross,rubik's 3x3 speed cube spin master games; rubik's toys brain games 681147035775 lphj723052 90011779 ptba33823 new,rubik's 3x3 speed cube rubik's itmyf3mehv 681147035775
2,2609,8544,1863,4,3477,Garten of Banban Mini Figure Set 4pk,Garten of Banban,Mini Figure Set,discounting,16.99,0.0255,0.085,19.99,3477,Garten of Banban Mini Figure Set 4pk,Garten of Banban,Mini Figure Set,discounting,16.99,0.0255,0.085,19.99,379,Garten of Banban Mini Figure Set - 4pk (Please be advised that sets may be missing pieces or otherwise incomplete.),Garten of Banban,,3,19.99,None,processed,approved,changed,created,good,None,,8,6,3,2025-08-28 17:44:48.115230+00:00,14,garten of banban mini figure set - 4pk (please be advised that sets may be missing pieces or otherwise incomplete.) ...,3,3,2025-08-25 15:41:47.600942+00:00,2025-08-28 17:44:48.116564+00:00,ITMEKA6GWJ,810087217662,approved,6656,2025-08-26 20:02:21.990020+00:00,Retag User,garten of banban mini figure set - 4pk (please be advised that sets may be missing pieces or otherwise incomplete.) ...,garten of banban mini figure set 4pk garten of banban mini figure set itmeka6gwj 810087217662

======================================================================
  inventory_product  (41,509 rows)
======================================================================

Columns:

           column_name                 data_type is_nullable column_default
0                   id                    bigint          NO           None
1                title         character varying          NO           None
2                brand         character varying          NO           None
3                model         character varying          NO           None
4      last_matched_at  timestamp with time zone         YES           None
5          match_count                   integer          NO           None
6   ai_suggested_title         character varying          NO           None
7        ai_confidence                   numeric         YES           None
8           created_at  timestamp with time zone          NO           None
9           updated_at  timestamp with time zone          NO           None
10    product_class_id                    bigint         YES           None

Foreign keys:

        column_name                 fk_table fk_column
0  product_class_id  inventory_product_class        id

Sample (3 rows):

,id,title,brand,model,last_matched_at,match_count,ai_suggested_title,ai_confidence,created_at,updated_at,product_class_id
0,2253,MTB Knee Pads Snowboard Knee Guards Low Temperature Resistance Breathable,MTB,N/A,None,0,,None,2025-08-25 14:27:55.191998+00:00,2025-08-25 14:37:49.547707+00:00,None
1,24099,Elanco Seresto,Elanco,N/A,None,0,,None,2025-10-16 15:42:32.686412+00:00,2025-10-16 15:42:32.686421+00:00,None
2,322,Seville Classics UltraHD Heavy-Duty Lockable Wall Storage Cabinet with Stainless Steel Doors,Seville Classics,UHD20229B,None,0,,None,2025-08-19 00:58:23.682625+00:00,2025-08-19 00:58:23.682631+00:00,None

======================================================================
  inventory_product_class  (0 rows)
======================================================================

Columns:

         column_name                 data_type is_nullable column_default
0                 id                    bigint          NO           None
1         class_name         character varying          NO           None
2  class_description                      text          NO           None
3          is_active                   boolean          NO           None
4         created_at  timestamp with time zone          NO           None
5         updated_at  timestamp with time zone          NO           None

======================================================================
  inventory_purchase_order  (103 rows)
======================================================================

Columns:

                   column_name                 data_type is_nullable column_default
0                           id                    bigint          NO           None
1                 order_number         character varying          NO           None
2                       status         character varying          NO           None
3                purchase_date                      date          NO           None
4            expected_delivery  timestamp with time zone         YES           None
5                received_date                      date         YES           None
6                 retail_value                   numeric          NO           None
7               purchase_price                   numeric          NO           None
8                   other_fees                   numeric          NO           None
9                shipping_cost                   numeric          NO           None
10                  total_cost                   numeric          NO           None
11                    quantity                   integer          NO           None
12                   condition         character varying          NO           None
13                 description                      text          NO           None
14                       notes                      text          NO           None
15           manifest_file_url         character varying         YES           None
16        manifest_uploaded_at  timestamp with time zone         YES           None
17           rows_generated_at  timestamp with time zone         YES           None
18  preprocessing_completed_at  timestamp with time zone         YES           None
19       processing_started_at  timestamp with time zone         YES           None
20     processing_completed_at  timestamp with time zone         YES           None
21                  created_at  timestamp with time zone          NO           None
22                  updated_at  timestamp with time zone          NO           None
23               created_by_id                    bigint         YES           None
24             csv_template_id                    bigint         YES           None
25             raw_manifest_id                    bigint         YES           None
26                   vendor_id                    bigint          NO           None

Foreign keys:

       column_name                fk_table fk_column
0  csv_template_id  inventory_csv_template        id
1  raw_manifest_id  inventory_raw_manifest        id
2        vendor_id        inventory_vendor        id
3    created_by_id               core_user        id

Sample (3 rows):

,id,order_number,status,purchase_date,expected_delivery,received_date,retail_value,purchase_price,other_fees,shipping_cost,total_cost,quantity,condition,description,notes,manifest_file_url,manifest_uploaded_at,rows_generated_at,preprocessing_completed_at,processing_started_at,processing_completed_at,created_at,updated_at,created_by_id,csv_template_id,raw_manifest_id,vendor_id
0,46,TRGET-OAG-4UL,items_generated,2025-09-07,2025-09-17 14:00:00+00:00,2025-09-18,14296.0,3625.0,145.0,740.99,4510.99,1059,good,"6 Pallets of Cleaning Supplies, Pet Supplies & More, 1,059 Units, Ext. Retail $14,296, Indianapolis, IN",,None,2025-09-10 16:51:32.406701+00:00,None,2025-09-17 18:05:23.831151+00:00,None,None,2025-09-10 16:51:20.938819+00:00,2025-09-17 18:05:23.831314+00:00,1,None,46,2
1,47,TRGET-OQN-QD80,items_generated,2025-09-07,2025-09-15 14:00:00+00:00,2025-09-16,37333.0,3825.0,153.0,2120.87,6098.87,548,good,"Truckload (26 Pallets) of Outdoor Living, Seasonal Items & More, 548 Units, Ext. Retail $37,333, Upper Marlboro, MD",Not paid as of 9/10 problem is on BStocks end,None,2025-09-10 17:01:02.165190+00:00,None,2025-09-16 16:00:20.491649+00:00,None,None,2025-09-10 17:00:40.092198+00:00,2025-09-16 16:00:20.491830+00:00,1,None,47,2
2,120,TRGET-O18-M7A0,items_generated,2025-10-20,2025-10-27 15:00:00+00:00,2025-10-27,75596.0,4136.0,206.8,1597.71,5940.51,2529,good,"Truckload (26 Pallets) of Home Décor, Bathroom Accessories & More, 2,529 Units, Ext. Retail $75,596, Indianapolis, IN",,None,2025-10-22 17:13:14.728060+00:00,None,2025-10-22 17:23:26.641911+00:00,None,None,2025-10-22 17:12:54.795508+00:00,2025-10-27 16:20:57.923487+00:00,1,None,110,2

======================================================================
  inventory_raw_manifest  (61 rows)
======================================================================

Columns:

        column_name                 data_type is_nullable column_default
0                id                    bigint          NO           None
1              name         character varying          NO           None
2         row_count                   integer          NO           None
3  header_signature                      text          NO           None
4       uploaded_at  timestamp with time zone          NO           None
5        s3_file_id                    bigint          NO           None
6    uploaded_by_id                    bigint         YES           None
7         vendor_id                    bigint         YES           None

Foreign keys:

      column_name          fk_table fk_column
0       vendor_id  inventory_vendor        id
1      s3_file_id      core_s3_file        id
2  uploaded_by_id         core_user        id

Sample (3 rows):

,id,name,row_count,header_signature,uploaded_at,s3_file_id,uploaded_by_id,vendor_id
0,3,Manifest for PO WAL135287,846,location|unit_retail|qty|ext_retail|upc|item|item_description|category|||,2025-08-22 18:32:04.514401+00:00,5,3,1
1,4,Manifest for PO TRGET-OKH-2VRC,2898,pallet_id|item|product_class|category_code|seller_category|item_description|qty|unit_retail|ext_retail|origin|upc|tc...,2025-08-25 14:49:19.940105+00:00,8,1,2
2,37,Manifest for PO CST569424,95,lot|item|dept_code|department|item_description|qty|unit_retail|ext_retail|vendor|category_code|category,2025-08-29 14:02:59.668590+00:00,41,1,35

======================================================================
  inventory_standardization_run  (62 rows)
======================================================================

Columns:

         column_name                 data_type is_nullable column_default
0                 id                    bigint          NO           None
1       rows_created                   integer          NO           None
2      configuration                     jsonb          NO           None
3         created_at  timestamp with time zone         YES           None
4      created_by_id                    bigint         YES           None
5  purchase_order_id                    bigint          NO           None
6   template_used_id                    bigint         YES           None

Foreign keys:

         column_name                  fk_table fk_column
0      created_by_id                 core_user        id
1  purchase_order_id  inventory_purchase_order        id
2   template_used_id    inventory_csv_template        id

Sample (3 rows):

,id,rows_created,configuration,created_at,created_by_id,purchase_order_id,template_used_id
0,2,319,"{'errors': [], 'template_id': 1, 'template_name': 'Walmart Template - Model, Category, UPC, Item#, PalletID, Dept', ...",2025-08-18 19:57:39.283394+00:00,1,2,1
1,3,846,"{'errors': [], 'template_id': 1, 'template_name': 'Walmart Template - Model, Category, UPC, Item#, PalletID, Dept', ...",2025-08-22 18:34:08.158816+00:00,3,3,1
2,4,2898,"{'errors': [], 'template_id': 3, 'template_name': 'Target - Category, Subcategory, UPC, ITEM #, TCIN, PalletID, Cond...",2025-08-25 14:52:27.998939+00:00,1,4,3

======================================================================
  inventory_store_configuration  (9 rows)
======================================================================

Columns:

     column_name                 data_type is_nullable column_default
0             id                    bigint          NO           None
1            key         character varying          NO           None
2          value                      text          NO           None
3    description         character varying          NO           None
4     updated_at  timestamp with time zone          NO           None
5  updated_by_id                    bigint         YES           None

Foreign keys:

     column_name   fk_table fk_column
0  updated_by_id  core_user        id

Sample (3 rows):

   id                 key                                     value            description                       updated_at updated_by_id
0   1        facebook_url  https://www.facebook.com/ecothrift.omaha      Facebook page URL 2025-10-07 21:38:51.659171+00:00          None
1   2       instagram_url                                            Instagram profile URL 2025-10-07 21:38:51.665657+00:00          None
2   3  google_reviews_url                                               Google Reviews URL 2025-10-07 21:38:51.670523+00:00          None

======================================================================
  inventory_vendor  (9 rows)
======================================================================

Columns:

      column_name                 data_type is_nullable column_default
0              id                    bigint          NO           None
1            name         character varying          NO           None
2            code         character varying          NO           None
3     vendor_type         character varying          NO           None
4    contact_name         character varying          NO           None
5           email         character varying          NO           None
6           phone         character varying          NO           None
7         website         character varying          NO           None
8   address_line1         character varying          NO           None
9   address_line2         character varying          NO           None
10           city         character varying          NO           None
11          state         character varying          NO           None
12       zip_code         character varying          NO           None
13     created_at  timestamp with time zone          NO           None
14     updated_at  timestamp with time zone          NO           None
15  created_by_id                    bigint         YES           None

Foreign keys:

     column_name   fk_table fk_column
0  created_by_id  core_user        id

Sample (3 rows):

,id,name,code,vendor_type,contact_name,email,phone,website,address_line1,address_line2,city,state,zip_code,created_at,updated_at,created_by_id
0,1,Walmart,WAL,liquidation,,,,https://liquidations.walmart.com/,,,,,,2025-08-18 17:54:20.384821+00:00,2025-08-18 17:54:20.384836+00:00,1
1,2,Target,TRGET,liquidation,,,,https://bstock.com/buy/seller/target,,,,,,2025-08-25 14:46:58.619332+00:00,2025-08-25 14:46:58.619347+00:00,1
2,35,Costco,CST,liquidation,,,,https://bstock.com/costco,,,,,,2025-08-29 14:01:52.779465+00:00,2025-08-29 14:01:52.779479+00:00,1

## 1B — DB2 POS / Sales tables

In [4]:
db2_pos_tables = [t for t in all_db2 if t.startswith("pos_") or "cart" in t or "sale" in t or "transaction" in t or "payment" in t]
print("POS/Sales tables:", db2_pos_tables)

for t in db2_pos_tables:
    cols_df, n = full_describe(eng2, t, sch2, sample_n=3)
    db2_schemas[t] = {"cols": set(cols_df["column_name"]), "n": n}

POS/Sales tables: ['pos_bank_transaction', 'pos_cart', 'pos_cart_line', 'pos_cash_deposit', 'pos_cash_management_settings', 'pos_change_request', 'pos_discount_rule', 'pos_drawer', 'pos_drawer_shift', 'pos_payment', 'pos_receipt', 'pos_receipt_template', 'pos_register', 'pos_revenue_goal', 'pos_supplemental_drawer', 'pos_supplemental_drawer_transaction', 'pos_transaction_void']

======================================================================
  pos_bank_transaction  (12 rows)
======================================================================

Columns:

                column_name                 data_type is_nullable column_default
0                        id                    bigint          NO           None
1          transaction_date                      date          NO           None
2          transaction_type         character varying          NO           None
3            deposit_amount                   numeric          NO           None
4             change_amount                   numeric          NO           None
5  bank_confirmation_number         character varying          NO           None
6                     notes                      text          NO           None
7                created_at  timestamp with time zone          NO           None
8           performed_by_id                    bigint         YES           None
9          work_location_id                    bigint          NO           None

Foreign keys:

        column_name            fk_table fk_column
0   performed_by_id           core_user        id
1  work_location_id  core_work_location        id

Sample (3 rows):

   id transaction_date transaction_type  deposit_amount  change_amount bank_confirmation_number notes                       created_at  performed_by_id  work_location_id
0   1       2025-09-18             both          4880.0          350.0                                2025-09-18 21:38:27.361709+00:00               19                 4
1   2       2025-10-04             both          4670.0          340.0                                2025-10-04 20:36:21.335267+00:00               19                 4
2   3       2025-10-04             both          1078.0           65.0                                2025-10-04 20:47:39.721796+00:00               19                 5

======================================================================
  pos_cart  (16,275 rows)
======================================================================

Columns:

        column_name                 data_type is_nullable column_default
0                id                    bigint          NO           None
1            status         character varying          NO           None
2          subtotal                   numeric          NO           None
3          tax_rate                   numeric          NO           None
4        tax_amount                   numeric          NO           None
5             total                   numeric          NO           None
6        created_at  timestamp with time zone          NO           None
7      completed_at  timestamp with time zone         YES           None
8        updated_at  timestamp with time zone          NO           None
9        cashier_id                    bigint          NO           None
10      customer_id                    bigint         YES           None
11        drawer_id                    bigint          NO           None
12  credit_card_fee                   numeric          NO           None

Foreign keys:

   column_name    fk_table fk_column
0   cashier_id   core_user        id
1  customer_id   core_user        id
2    drawer_id  pos_drawer        id

Sample (3 rows):

,id,status,subtotal,tax_rate,tax_amount,total,created_at,completed_at,updated_at,cashier_id,customer_id,drawer_id,credit_card_fee
0,52,completed,10.00,0.07,0.70,10.70,2025-08-23 19:11:16.165851+00:00,2025-08-23 19:11:49.150576+00:00,2025-08-23 19:11:49.150628+00:00,3,None,1,0.0
1,2,active,0.00,0.07,0.00,0.00,2025-08-23 14:15:53.601159+00:00,NaT,2025-08-23 14:16:03.719384+00:00,3,None,1,0.0
2,42,completed,33.64,0.07,2.35,35.99,2025-08-23 17:42:43.157788+00:00,2025-08-23 17:43:28.915338+00:00,2025-08-23 17:43:28.915412+00:00,3,None,1,0.0

======================================================================
  pos_cart_line  (42,586 rows)
======================================================================

Columns:

         column_name                 data_type is_nullable column_default
0                 id                    bigint          NO           None
1           quantity                   integer          NO           None
2         unit_price                   numeric          NO           None
3         line_total                   numeric          NO           None
4      product_title         character varying          NO           None
5      product_brand         character varying          NO           None
6      product_model         character varying          NO           None
7         created_at  timestamp with time zone          NO           None
8            cart_id                    bigint          NO           None
9            item_id                    bigint         YES           None
10  discount_rule_id                    bigint         YES           None

Foreign keys:

        column_name           fk_table fk_column
0           cart_id           pos_cart        id
1  discount_rule_id  pos_discount_rule        id
2           item_id     inventory_item        id

Sample (3 rows):

   id  quantity  unit_price  line_total                       product_title product_brand product_model                       created_at  cart_id  item_id discount_rule_id
0   2         1      185.80      185.80              Ladies' Watch - 98L323        Bulova               2025-08-23 14:17:19.082351+00:00        1     4538             None
1   3         1      295.61      295.61                          Alternator      Unbraded        939184 2025-08-23 14:17:23.886022+00:00        1     4096             None
2   4         1       25.34       25.34  Easy Touch 5 Dash WindSheild Mount      Unbraded        939184 2025-08-23 14:17:27.423072+00:00        1     5839             None

======================================================================
  pos_cash_deposit  (13 rows)
======================================================================

Columns:

           column_name                 data_type is_nullable column_default
0                   id                    bigint          NO           None
1         deposit_date                      date          NO           None
2               amount                   numeric          NO           None
3   denomination_count                     jsonb          NO           None
4               status         character varying          NO           None
5                notes                      text          NO           None
6           created_at  timestamp with time zone          NO           None
7  bank_transaction_id                    bigint         YES           None
8        created_by_id                    bigint         YES           None
9     work_location_id                    bigint          NO           None

Foreign keys:

           column_name              fk_table fk_column
0  bank_transaction_id  pos_bank_transaction        id
1        created_by_id             core_user        id
2     work_location_id    core_work_location        id

Sample (3 rows):

,id,deposit_date,amount,denomination_count,status,notes,created_at,bank_transaction_id,created_by_id,work_location_id
0,1,2025-09-18,3620.0,"{'ones': 0, 'tens': 20, 'dimes': 0, 'fives': 0, 'fifties': 4, 'nickels': 0, 'pennies': 0, 'hundreds': 14, 'quarters'...",deposited,deposit done,2025-09-18 21:38:27.363995+00:00,1,19,4
1,2,2025-09-18,1260.0,"{'ones': 0, 'tens': 15, 'dimes': 0, 'fives': 0, 'fifties': 1, 'nickels': 0, 'pennies': 0, 'hundreds': 3, 'quarters':...",deposited,Deposit done,2025-09-18 21:38:27.365468+00:00,1,19,5
2,3,2025-10-04,2690.0,"{'ones': 0, 'tens': 0, 'dimes': 0, 'fives': 0, 'fifties': 5, 'nickels': 0, 'pennies': 0, 'hundreds': 12, 'quarters':...",deposited,,2025-10-04 20:36:21.338463+00:00,2,19,4

======================================================================
  pos_cash_management_settings  (5 rows)
======================================================================

Columns:

                         column_name                 data_type is_nullable column_default
0                                 id                    bigint          NO           None
1   max_variance_without_explanation                   numeric          NO           None
2      max_variance_without_approval                   numeric          NO           None
3             auto_deposit_threshold                   numeric          NO           None
4                 min_deposit_amount                   numeric          NO           None
5      auto_change_request_threshold                   numeric          NO           None
6          default_register_hundreds                   integer          NO           None
7           default_register_fifties                   integer          NO           None
8          default_register_twenties                   integer          NO           None
9              default_register_tens                   integer          NO           None
10            default_register_fives                   integer          NO           None
11             default_register_ones                   integer          NO           None
12         default_register_quarters                   integer          NO           None
13            default_register_dimes                   integer          NO           None
14          default_register_nickels                   integer          NO           None
15          default_register_pennies                   integer          NO           None
16       ideal_supplemental_hundreds                   integer          NO           None
17        ideal_supplemental_fifties                   integer          NO           None
18       ideal_supplemental_twenties                   integer          NO           None
19           ideal_supplemental_tens                   integer          NO           None
20          ideal_supplemental_fives                   integer          NO           None
21           ideal_supplemental_ones                   integer          NO           None
22       ideal_supplemental_quarters                   integer          NO           None
23          ideal_supplemental_dimes                   integer          NO           None
24        ideal_supplemental_nickels                   integer          NO           None
25        ideal_supplemental_pennies                   integer          NO           None
26               require_blind_count                   boolean          NO           None
27                require_dual_count                   boolean          NO           None
28                 allow_force_close                   boolean          NO           None
29           auto_create_next_drawer                   boolean          NO           None
30                        created_at  timestamp with time zone          NO           None
31                        updated_at  timestamp with time zone          NO           None
32                     updated_by_id                    bigint         YES           None
33                  work_location_id                    bigint          NO           None

Foreign keys:

        column_name            fk_table fk_column
0     updated_by_id           core_user        id
1  work_location_id  core_work_location        id

Sample (3 rows):

,id,max_variance_without_explanation,max_variance_without_approval,auto_deposit_threshold,min_deposit_amount,auto_change_request_threshold,default_register_hundreds,default_register_fifties,default_register_twenties,default_register_tens,default_register_fives,default_register_ones,default_register_quarters,default_register_dimes,default_register_nickels,default_register_pennies,ideal_supplemental_hundreds,ideal_supplemental_fifties,ideal_supplemental_twenties,ideal_supplemental_tens,ideal_supplemental_fives,ideal_supplemental_ones,ideal_supplemental_quarters,ideal_supplemental_dimes,ideal_supplemental_nickels,ideal_supplemental_pennies,require_blind_count,require_dual_count,allow_force_close,auto_create_next_drawer,created_at,updated_at,updated_by_id,work_location_id
0,1,5.0,20.0,2000.0,500.0,0.5,0,0,10,10,10,50,40,50,40,100,5,4,25,30,40,200,200,500,200,1000,False,False,True,True,2025-09-12 02:35:30.598343+00:00,2025-09-12 02:35:30.598353+00:00,1.0,4
1,2,5.0,20.0,2000.0,500.0,0.5,0,0,10,10,10,50,40,50,40,100,5,4,25,30,40,200,200,500,200,1000,False,False,True,True,2025-09-12 02:35:30.610152+00:00,2025-09-12 02:35:30.610162+00:00,1.0,5
2,3,5.0,20.0,2000.0,500.0,0.5,0,0,10,10,10,50,40,50,40,100,5,4,25,30,40,200,200,500,200,1000,False,False,True,True,2025-09-12 02:35:31.170414+00:00,2025-09-12 02:35:31.170428+00:00,NaN,1

======================================================================
  pos_change_request  (13 rows)
======================================================================

Columns:

            column_name                 data_type is_nullable column_default
0                    id                    bigint          NO           None
1          request_date                      date          NO           None
2    denomination_count                     jsonb          NO           None
3          total_amount                   numeric          NO           None
4                status         character varying          NO           None
5          fulfilled_at  timestamp with time zone         YES           None
6                 notes                      text          NO           None
7            created_at  timestamp with time zone          NO           None
8   bank_transaction_id                    bigint         YES           None
9         created_by_id                    bigint         YES           None
10     work_location_id                    bigint          NO           None

Foreign keys:

           column_name              fk_table fk_column
0  bank_transaction_id  pos_bank_transaction        id
1        created_by_id             core_user        id
2     work_location_id    core_work_location        id

Sample (3 rows):

,id,request_date,denomination_count,total_amount,status,fulfilled_at,notes,created_at,bank_transaction_id,created_by_id,work_location_id
0,1,2025-09-18,"{'ones': 100, 'tens': 0, 'dimes': 100, 'fives': 20, 'fifties': 0, 'nickels': 0, 'pennies': 0, 'hundreds': 0, 'quarte...",260.0,fulfilled,2025-09-18 21:38:27.366348+00:00,,2025-09-18 21:38:27.366600+00:00,1,19,4
1,2,2025-09-18,"{'ones': 20, 'tens': 0, 'dimes': 0, 'fives': 14, 'fifties': 0, 'nickels': 0, 'pennies': 0, 'hundreds': 0, 'quarters'...",90.0,fulfilled,2025-09-18 21:38:27.368138+00:00,,2025-09-18 21:38:27.368296+00:00,1,19,5
2,3,2025-10-04,"{'ones': 100, 'tens': 0, 'dimes': 150, 'fives': 20, 'fifties': 0, 'nickels': 80, 'pennies': 100, 'hundreds': 0, 'qua...",240.0,fulfilled,2025-10-04 20:36:21.340102+00:00,,2025-10-04 20:36:21.340286+00:00,2,19,4

======================================================================
  pos_discount_rule  (2 rows)
======================================================================

Columns:

       column_name                 data_type is_nullable column_default
0               id                    bigint          NO           None
1             name         character varying          NO           None
2      button_text         character varying          NO           None
3      description                      text          NO           None
4    discount_type         character varying          NO           None
5   discount_value                   numeric          NO           None
6     min_purchase                   numeric          NO           None
7        is_active                   boolean          NO           None
8       start_date  timestamp with time zone         YES           None
9         end_date  timestamp with time zone         YES           None
10      created_at  timestamp with time zone          NO           None
11      updated_at  timestamp with time zone          NO           None
12   created_by_id                    bigint         YES           None

Foreign keys:

     column_name   fk_table fk_column
0  created_by_id  core_user        id

Sample (2 rows):

,id,name,button_text,description,discount_type,discount_value,min_purchase,is_active,start_date,end_date,created_at,updated_at,created_by_id
0,2,"GRAND OPENING: $200 Off $1,000 Purchase","$200 off $1,000","GRAND OPENING - $200 off $1,000 purchase\nCanfield on October 11th - 12th, 2025",flat_amount,200.0,1000.0,True,2025-10-10 05:00:00+00:00,2025-10-12 16:00:00+00:00,2025-10-11 01:27:17.411230+00:00,2025-10-10 20:27:41.642439-05:00,1
1,1,GRAND OPENING: $15 Off $100 Purchase,$15 off $100,"GRAND OPENING: $15 Off $100 Purchase\nCanfield on October 11th - 12th, 2025",flat_amount,15.0,100.0,True,2025-10-10 05:00:00+00:00,2025-10-13 04:55:00+00:00,2025-10-11 01:24:57.158262+00:00,2025-12-08 10:25:45.339281-06:00,1

======================================================================
  pos_drawer  (229 rows)
======================================================================

Columns:

     column_name                 data_type is_nullable column_default
0             id                    bigint          NO           None
1      opened_at  timestamp with time zone          NO           None
2      closed_at  timestamp with time zone         YES           None
3   opening_cash                   numeric          NO           None
4   closing_cash                   numeric         YES           None
5  expected_cash                   numeric         YES           None
6          notes                      text          NO           None
7     cashier_id                    bigint          NO           None
8    register_id                    bigint          NO           None
9    drawer_date                      date          NO           None

Foreign keys:

   column_name      fk_table fk_column
0   cashier_id     core_user        id
1  register_id  pos_register        id

Sample (3 rows):

,id,opened_at,closed_at,opening_cash,closing_cash,expected_cash,notes,cashier_id,register_id,drawer_date
0,49,2025-09-18 13:58:01.411156+00:00,2025-09-18 21:07:20.334381+00:00,241.49,276.18,276.18,Drawer opened at Default Register by EMP25003\nShift opened by EMP25017 - Variance: $34.69,19,4,2025-09-18
1,1,2025-08-23 14:03:16.637172+00:00,NaT,200.00,NaN,970.41,,3,1,2025-08-23
2,2,2025-08-23 21:29:47.485377+00:00,NaT,200.00,NaN,200.00,\nAuto-closed during migration (duplicate open drawer),4,1,2025-08-23

======================================================================
  pos_drawer_shift  (963 rows)
======================================================================

Columns:

            column_name                 data_type is_nullable column_default
0                    id                    bigint          NO           None
1                  type         character varying          NO           None
2          counted_cash                   numeric          NO           None
3         expected_cash                   numeric          NO           None
4              variance                   numeric          NO           None
5        cash_breakdown                     jsonb          NO           None
6       variance_reason                      text          NO           None
7     variance_approved                   boolean          NO           None
8            created_at  timestamp with time zone          NO           None
9             drawer_id                    bigint          NO           None
10       new_cashier_id                    bigint         YES           None
11  previous_cashier_id                    bigint         YES           None
12       verified_by_id                    bigint         YES           None
13             ended_at  timestamp with time zone         YES           None

Foreign keys:

           column_name    fk_table fk_column
0            drawer_id  pos_drawer        id
1       new_cashier_id   core_user        id
2  previous_cashier_id   core_user        id
3       verified_by_id   core_user        id

Sample (3 rows):

,id,type,counted_cash,expected_cash,variance,cash_breakdown,variance_reason,variance_approved,created_at,drawer_id,new_cashier_id,previous_cashier_id,verified_by_id,ended_at
0,1,shift_start,1.00,1.00,0.00,"{'ones': 1, 'tens': 0, 'dimes': 0, 'fives': 0, 'fifties': 0, 'nickels': 0, 'pennies': 0, 'hundreds': 0, 'quarters': ...",,False,2025-09-12 02:37:03.204368+00:00,35,1.0,NaN,None,NaT
1,2,shift_end,1.11,1.11,0.00,"{'ones': 1, 'tens': 0, 'dimes': 1, 'fives': 0, 'fifties': 0, 'nickels': 0, 'pennies': 1, 'hundreds': 0, 'quarters': ...",,False,2025-09-12 02:37:51.371845+00:00,35,NaN,1.0,None,2025-09-12 02:37:51.371614+00:00
2,3,drawer_close,1.11,1.00,0.11,"{'ones': 1, 'tens': 0, 'dimes': 1, 'fives': 0, 'fifties': 0, 'nickels': 0, 'pennies': 1, 'hundreds': 0, 'quarters': ...",,False,2025-09-12 02:38:17.364483+00:00,35,1.0,1.0,None,2025-09-12 02:38:17.364266+00:00

======================================================================
  pos_payment  (15,306 rows)
======================================================================

Columns:

        column_name                 data_type is_nullable column_default
0                id                    bigint          NO           None
1    payment_method         character varying          NO           None
2            amount                   numeric          NO           None
3   amount_tendered                   numeric         YES           None
4      change_given                   numeric         YES           None
5  reference_number         character varying          NO           None
6      processed_at  timestamp with time zone          NO           None
7           cart_id                    bigint          NO           None
8         card_type         character varying         YES           None

Foreign keys:

  column_name  fk_table fk_column
0     cart_id  pos_cart        id

Sample (3 rows):

   id payment_method  amount amount_tendered change_given reference_number                     processed_at  cart_id card_type
0   1           card   31.62            None         None                  2025-08-23 14:21:22.137061+00:00        4      None
1   2           card   31.62            None         None                  2025-08-23 14:22:29.763106+00:00        5      None
2   3           card  236.03            None         None                  2025-08-23 15:11:11.626755+00:00        9      None

======================================================================
  pos_receipt  (15,306 rows)
======================================================================

Columns:

          column_name                 data_type is_nullable column_default
0                  id                    bigint          NO           None
1      receipt_number         character varying          NO           None
2             printed                   boolean          NO           None
3          printed_at  timestamp with time zone         YES           None
4        printer_name         character varying          NO           None
5             emailed                   boolean          NO           None
6          emailed_at  timestamp with time zone         YES           None
7       email_address         character varying          NO           None
8          created_at  timestamp with time zone          NO           None
9             cart_id                    bigint          NO           None
10  customer_declined                   boolean          NO           None

Foreign keys:

  column_name  fk_table fk_column
0     cart_id  pos_cart        id

Sample (3 rows):

   id receipt_number  printed                       printed_at     printer_name  emailed emailed_at email_address                       created_at  cart_id  customer_declined
0   1  R202508230001     True 2025-08-23 14:21:22.358548+00:00  Receipt Printer    False       None               2025-08-23 14:21:22.148993+00:00        4              False
1   2  R202508230002     True 2025-08-23 14:22:29.962321+00:00  Receipt Printer    False       None               2025-08-23 14:22:29.773090+00:00        5              False
2   3  R202508230003     True 2025-08-23 15:11:11.864552+00:00  Receipt Printer    False       None               2025-08-23 15:11:11.650079+00:00        9              False

======================================================================
  pos_receipt_template  (0 rows)
======================================================================

Columns:

           column_name                 data_type is_nullable column_default
0                   id                    bigint          NO           None
1                 name         character varying          NO           None
2          description                      text          NO           None
3          header_text                      text          NO           None
4        store_address                      text          NO           None
5          store_phone         character varying          NO           None
6            show_logo                   boolean          NO           None
7          footer_text                      text          NO           None
8   show_return_policy                   boolean          NO           None
9   return_policy_text                      text          NO           None
10         paper_width                   integer          NO           None
11           font_size         character varying          NO           None
12     include_qr_code                   boolean          NO           None
13     include_barcode                   boolean          NO           None
14   show_cashier_name                   boolean          NO           None
15       show_item_sku                   boolean          NO           None
16          is_default                   boolean          NO           None
17           is_active                   boolean          NO           None
18          created_at  timestamp with time zone          NO           None
19          updated_at  timestamp with time zone          NO           None
20       created_by_id                    bigint         YES           None

Foreign keys:

     column_name   fk_table fk_column
0  created_by_id  core_user        id

======================================================================
  pos_register  (5 rows)
======================================================================

Columns:

         column_name                 data_type is_nullable column_default
0                 id                    bigint          NO           None
1               name         character varying          NO           None
2               code         character varying          NO           None
3          is_active                   boolean          NO           None
4         created_at  timestamp with time zone          NO           None
5              notes                      text          NO           None
6   work_location_id                    bigint          NO           None
7        description                      text          NO           None
8        ideal_dimes                   integer          NO           None
9      ideal_fifties                   integer          NO           None
10       ideal_fives                   integer          NO           None
11    ideal_hundreds                   integer          NO           None
12     ideal_nickels                   integer          NO           None
13        ideal_ones                   integer          NO           None
14     ideal_pennies                   integer          NO           None
15    ideal_quarters                   integer          NO           None
16        ideal_tens                   integer          NO           None
17    ideal_twenties                   integer          NO           None

Foreign keys:

        column_name            fk_table fk_column
0  work_location_id  core_work_location        id

Sample (3 rows):

,id,name,code,is_active,created_at,notes,work_location_id,description,ideal_dimes,ideal_fifties,ideal_fives,ideal_hundreds,ideal_nickels,ideal_ones,ideal_pennies,ideal_quarters,ideal_tens,ideal_twenties
0,1,Default Register,DEFAULT,True,2025-09-12 02:35:27.978595+00:00,Auto-created for migration,3,,50,0,10,0,40,50,100,40,10,10
1,2,Register 1,RET-APP-REG01,True,2025-09-12 02:35:30.510875+00:00,Auto-created by migration,4,Register 1 at Retail - Applewood,50,0,10,0,40,50,100,40,10,10
2,3,Register 2,RET-APP-REG02,True,2025-09-12 02:35:30.510875+00:00,Auto-created by migration,4,Register 2 at Retail - Applewood,50,0,10,0,40,50,100,40,10,10

======================================================================
  pos_revenue_goal  (182 rows)
======================================================================

Columns:

        column_name                 data_type is_nullable column_default
0                id                    bigint          NO           None
1              date                      date          NO           None
2       goal_amount                   numeric          NO           None
3             notes                      text          NO           None
4        created_at  timestamp with time zone          NO           None
5        updated_at  timestamp with time zone          NO           None
6     created_by_id                    bigint         YES           None
7  work_location_id                    bigint          NO           None

Foreign keys:

        column_name            fk_table fk_column
0     created_by_id           core_user        id
1  work_location_id  core_work_location        id

Sample (3 rows):

   id        date  goal_amount                        notes                       created_at                       updated_at created_by_id  work_location_id
0   1  2025-09-18       3000.0  Auto-generated default goal 2025-09-18 20:41:25.875044+00:00 2025-09-18 20:41:25.875051+00:00          None                 4
1   2  2025-09-18       3000.0  Auto-generated default goal 2025-09-18 20:41:25.877797+00:00 2025-09-18 20:41:25.877804+00:00          None                 5
2   3  2025-09-19       5000.0  Auto-generated default goal 2025-09-18 20:41:25.879510+00:00 2025-09-18 20:41:25.879516+00:00          None                 4

======================================================================
  pos_supplemental_drawer  (5 rows)
======================================================================

Columns:

         column_name                 data_type is_nullable column_default
0                 id                    bigint          NO           None
1     ideal_hundreds                   integer          NO           None
2      ideal_fifties                   integer          NO           None
3     ideal_twenties                   integer          NO           None
4         ideal_tens                   integer          NO           None
5        ideal_fives                   integer          NO           None
6         ideal_ones                   integer          NO           None
7     ideal_quarters                   integer          NO           None
8        ideal_dimes                   integer          NO           None
9      ideal_nickels                   integer          NO           None
10     ideal_pennies                   integer          NO           None
11  current_hundreds                   integer          NO           None
12   current_fifties                   integer          NO           None
13  current_twenties                   integer          NO           None
14      current_tens                   integer          NO           None
15     current_fives                   integer          NO           None
16      current_ones                   integer          NO           None
17  current_quarters                   integer          NO           None
18     current_dimes                   integer          NO           None
19   current_nickels                   integer          NO           None
20   current_pennies                   integer          NO           None
21     last_verified  timestamp with time zone         YES           None
22        created_at  timestamp with time zone          NO           None
23        updated_at  timestamp with time zone          NO           None
24    verified_by_id                    bigint         YES           None
25  work_location_id                    bigint          NO           None

Foreign keys:

        column_name            fk_table fk_column
0  work_location_id  core_work_location        id
1    verified_by_id           core_user        id

Sample (3 rows):

,id,ideal_hundreds,ideal_fifties,ideal_twenties,ideal_tens,ideal_fives,ideal_ones,ideal_quarters,ideal_dimes,ideal_nickels,ideal_pennies,current_hundreds,current_fifties,current_twenties,current_tens,current_fives,current_ones,current_quarters,current_dimes,current_nickels,current_pennies,last_verified,created_at,updated_at,verified_by_id,work_location_id
0,1,5,4,25,30,40,200,200,500,200,1000,5,4,25,30,40,200,200,500,200,1000,2025-09-11 05:00:00+00:00,2025-09-12 02:35:30.593307+00:00,2025-09-12 02:35:30.593319+00:00,1.0,4
1,3,5,4,25,30,40,200,200,500,200,1000,5,4,25,30,40,200,200,500,200,1000,NaT,2025-09-12 02:35:31.174351+00:00,2025-09-12 02:35:31.174361+00:00,NaN,1
2,4,5,4,25,30,40,200,200,500,200,1000,5,4,25,30,40,200,200,500,200,1000,NaT,2025-09-12 02:35:31.182337+00:00,2025-09-12 02:35:31.182345+00:00,NaN,2

======================================================================
  pos_supplemental_drawer_transaction  (13 rows)
======================================================================

Columns:

            column_name                 data_type is_nullable column_default
0                    id                    bigint          NO           None
1      transaction_type         character varying          NO           None
2      transaction_date                      date          NO           None
3               cash_in                   numeric          NO           None
4              cash_out                   numeric          NO           None
5   denomination_before                     jsonb          NO           None
6    denomination_after                     jsonb          NO           None
7         balance_after                   numeric          NO           None
8           description                      text          NO           None
9            created_at  timestamp with time zone          NO           None
10      performed_by_id                    bigint         YES           None
11    related_drawer_id                    bigint         YES           None
12     work_location_id                    bigint          NO           None
13      cash_deposit_id                    bigint         YES           None
14     denomination_out                     jsonb          NO           None

Foreign keys:

         column_name            fk_table fk_column
0    cash_deposit_id    pos_cash_deposit        id
1    performed_by_id           core_user        id
2  related_drawer_id          pos_drawer        id
3   work_location_id  core_work_location        id

Sample (3 rows):

,id,transaction_type,transaction_date,cash_in,cash_out,denomination_before,denomination_after,balance_after,description,created_at,performed_by_id,related_drawer_id,work_location_id,cash_deposit_id,denomination_out
0,1,drawer_exchange,2025-09-11,0.0,0.0,"{'ones': 0, 'tens': 0, 'dimes': 0, 'fives': 0, 'fifties': 0, 'nickels': 0, 'pennies': 0, 'hundreds': 0, 'quarters': ...","{'ones': 0, 'tens': 0, 'dimes': 0, 'fives': 0, 'fifties': 0, 'nickels': 0, 'pennies': 0, 'hundreds': 0, 'quarters': ...",0.0,End of day exchange for Default Register,2025-09-12 02:38:27.604046+00:00,1,35,3,None,{}
1,2,drawer_exchange,2025-09-13,165.0,31.0,"{'ones': 200, 'tens': 30, 'dimes': 500, 'fives': 40, 'fifties': 4, 'nickels': 200, 'pennies': 1000, 'hundreds': 5, '...","{'ones': 197, 'tens': 29, 'dimes': 450, 'fives': 41, 'fifties': 4, 'nickels': 160, 'pennies': 900, 'hundreds': 5, 'q...",2154.0,End of day exchange for Register 1,2025-09-13 16:18:08.147672+00:00,19,37,5,None,{}
2,4,drawer_exchange,2025-09-13,10.0,70.0,"{'ones': 194, 'tens': 28, 'dimes': 450, 'fives': 40, 'fifties': 4, 'nickels': 160, 'pennies': 900, 'hundreds': 5, 'q...","{'ones': 194, 'tens': 27, 'dimes': 450, 'fives': 42, 'fifties': 4, 'nickels': 160, 'pennies': 900, 'hundreds': 5, 'q...",1916.0,End of day exchange for Register 1,2025-09-14 01:10:40.023546+00:00,19,39,5,None,{}

======================================================================
  pos_transaction_void  (7 rows)
======================================================================

Columns:

         column_name                 data_type is_nullable column_default
0                 id                    bigint          NO           None
1          void_type         character varying          NO           None
2        manager_pin         character varying          NO           None
3             reason                      text          NO           None
4      refund_amount                   numeric          NO           None
5     items_returned                     jsonb          NO           None
6           approved                   boolean          NO           None
7          completed                   boolean          NO           None
8         created_at  timestamp with time zone          NO           None
9       completed_at  timestamp with time zone         YES           None
10    approved_by_id                    bigint         YES           None
11       new_cart_id                    bigint         YES           None
12  original_cart_id                    bigint          NO           None
13   requested_by_id                    bigint         YES           None

Foreign keys:

        column_name   fk_table fk_column
0    approved_by_id  core_user        id
1       new_cart_id   pos_cart        id
2  original_cart_id   pos_cart        id
3   requested_by_id  core_user        id

Sample (3 rows):

,id,void_type,manager_pin,reason,refund_amount,items_returned,approved,completed,created_at,completed_at,approved_by_id,new_cart_id,original_cart_id,requested_by_id
0,1,void,1234,TESTING,0.0,[],True,True,2025-08-23 13:58:39.102843-05:00,2025-08-23 18:58:39.174177+00:00,3.0,None,5,3
1,2,void,1234,TESTING,0.0,[],True,True,2025-08-23 13:58:48.257973-05:00,2025-08-23 18:58:48.317190+00:00,3.0,None,4,3
2,34,void,6661,i hate it,0.0,[],False,False,2026-01-21 14:31:19.594376-06:00,NaT,NaN,None,14200,23

## 1C — DB2 Other potentially relevant tables
Anything with order, manifest, vendor, csv, template, category in the name that wasn't already covered.

In [5]:
already = set(db2_inv_tables + db2_pos_tables)
keywords = ["order", "manifest", "vendor", "csv", "template", "categ", "core_"]
db2_other = [t for t in all_db2 if t not in already and any(k in t.lower() for k in keywords)]
print("Other relevant tables:", db2_other)

for t in db2_other:
    cols_df, n = full_describe(eng2, t, sch2, sample_n=3)
    db2_schemas[t] = {"cols": set(cols_df["column_name"]), "n": n}

Other relevant tables: ['core_address', 'core_business_event', 'core_contact', 'core_customer_profile', 'core_employee_profile', 'core_event_category', 'core_manifest', 'core_s3_file', 'core_user', 'core_user_groups', 'core_user_user_permissions', 'core_work_location']

======================================================================
  core_address  (23 rows)
======================================================================

Columns:

        column_name                 data_type is_nullable column_default
0                id                    bigint          NO           None
1         object_id                   integer         YES           None
2      address_type         character varying          NO           None
3    address_line_1         character varying          NO           None
4    address_line_2         character varying          NO           None
5              city         character varying          NO           None
6             state         character varying          NO           None
7          zip_code         character varying          NO           None
8           country         character varying          NO           None
9        created_at  timestamp with time zone          NO           None
10       updated_at  timestamp with time zone          NO           None
11  content_type_id                   integer         YES           None

Foreign keys:

       column_name             fk_table fk_column
0  content_type_id  django_content_type        id

Sample (3 rows):

   id object_id address_type    address_line_1 address_line_2   city state zip_code country                       created_at                       updated_at content_type_id
0   1      None         work     8052 H Street                 Omaha    NE    68127      US 2025-08-19 21:14:23.825995+00:00 2025-08-19 21:14:23.826022+00:00            None
1   2      None         work     8072 H Street                 Omaha    NE    68127      US 2025-08-19 21:14:23.835835+00:00 2025-08-19 21:14:23.835848+00:00            None
2   3      None         work  8024 West Center                 Omaha    NE    68124      US 2025-08-19 21:14:23.843370+00:00 2025-08-19 21:14:23.843378+00:00            None

======================================================================
  core_business_event  (0 rows)
======================================================================

Columns:

        column_name                 data_type is_nullable column_default
0                id                    bigint          NO           None
1             level         character varying          NO           None
2        event_type         character varying          NO           None
3       description                      text          NO           None
4         object_id                   integer          NO           None
5          metadata                     jsonb          NO           None
6        ip_address                      inet         YES           None
7        user_agent                      text          NO           None
8        created_at  timestamp with time zone          NO           None
9          actor_id                    bigint         YES           None
10  content_type_id                   integer          NO           None
11   target_user_id                    bigint         YES           None
12      category_id                    bigint          NO           None

Foreign keys:

       column_name             fk_table fk_column
0         actor_id            core_user        id
1      category_id  core_event_category        id
2  content_type_id  django_content_type        id
3   target_user_id            core_user        id

======================================================================
  core_contact  (0 rows)
======================================================================

Columns:

       column_name                 data_type is_nullable column_default
0               id                    bigint          NO           None
1        object_id                   integer          NO           None
2     contact_type         character varying          NO           None
3    contact_value         character varying          NO           None
4            label         character varying          NO           None
5       is_primary                   boolean          NO           None
6       created_at  timestamp with time zone          NO           None
7       updated_at  timestamp with time zone          NO           None
8  content_type_id                   integer          NO           None

Foreign keys:

       column_name             fk_table fk_column
0  content_type_id  django_content_type        id

======================================================================
  core_customer_profile  (0 rows)
======================================================================

Columns:

       column_name                 data_type is_nullable column_default
0               id                    bigint          NO           None
1  customer_number         character varying          NO           None
2   customer_since                      date          NO           None
3     loyalty_tier         character varying          NO           None
4     email_opt_in                   boolean          NO           None
5       sms_opt_in                   boolean          NO           None
6   lifetime_spent                   numeric          NO           None
7       created_at  timestamp with time zone          NO           None
8       updated_at  timestamp with time zone          NO           None
9          user_id                    bigint          NO           None

Foreign keys:

  column_name   fk_table fk_column
0     user_id  core_user        id

======================================================================
  core_employee_profile  (39 rows)
======================================================================

Columns:

         column_name                 data_type is_nullable column_default
0                 id                    bigint          NO           None
1    employee_number         character varying          NO           None
2           position         character varying          NO           None
3    employment_type         character varying          NO           None
4          hire_date                      date          NO           None
5   termination_date                      date         YES           None
6         created_at  timestamp with time zone          NO           None
7         updated_at  timestamp with time zone          NO           None
8      department_id                    bigint         YES           None
9         manager_id                    bigint         YES           None
10      pay_grade_id                    bigint         YES           None
11           user_id                    bigint          NO           None

Foreign keys:

     column_name       fk_table fk_column
0  department_id  hr_department        id
1     manager_id      core_user        id
2   pay_grade_id   hr_pay_grade        id
3        user_id      core_user        id

Sample (3 rows):

   id employee_number          position employment_type   hire_date termination_date                       created_at                       updated_at  department_id manager_id pay_grade_id  user_id
0   3       EMP257015  Retag Specialist       part_time  2025-08-19             None 2025-08-19 21:27:45.204090+00:00 2025-08-19 21:27:45.204100+00:00            2.0       None         None        3
1   4       EMP014609      New Employee       full_time  2025-08-23             None 2025-08-23 19:16:57.892166+00:00 2025-08-23 19:16:57.892175+00:00            NaN       None         None        4
2   1       EMP257014      New Employee       full_time  2022-06-01             None 2025-08-18 17:53:43.831612+00:00 2025-08-26 20:14:43.926332+00:00            6.0       None         None        1

======================================================================
  core_event_category  (0 rows)
======================================================================

Columns:

      column_name                 data_type is_nullable column_default
0              id                    bigint          NO           None
1            name         character varying          NO           None
2     description                      text          NO           None
3  retention_days                   integer          NO           None
4      created_at  timestamp with time zone          NO           None
5      updated_at  timestamp with time zone          NO           None

======================================================================
  core_manifest  (0 rows)
======================================================================

Columns:

       column_name                 data_type is_nullable column_default
0               id                    bigint          NO           None
1             name         character varying          NO           None
2             type         character varying          NO           None
3        row_count                   integer          NO           None
4     column_names                     jsonb          NO           None
5      uploaded_at  timestamp with time zone          NO           None
6        processed                   boolean          NO           None
7     processed_at  timestamp with time zone         YES           None
8    error_message                      text          NO           None
9            notes                      text          NO           None
10  uploaded_by_id                    bigint         YES           None
11      s3_file_id                    bigint          NO           None

Foreign keys:

      column_name      fk_table fk_column
0      s3_file_id  core_s3_file        id
1  uploaded_by_id     core_user        id

======================================================================
  core_s3_file  (68 rows)
======================================================================

Columns:

      column_name                 data_type is_nullable column_default
0              id                    bigint          NO           None
1             key         character varying          NO           None
2        filename         character varying          NO           None
3            size                    bigint          NO           None
4    content_type         character varying          NO           None
5     uploaded_at  timestamp with time zone          NO           None
6        metadata                     jsonb          NO           None
7       is_public                   boolean          NO           None
8     description                      text          NO           None
9  uploaded_by_id                    bigint         YES           None

Foreign keys:

      column_name   fk_table fk_column
0  uploaded_by_id  core_user        id

Sample (3 rows):

,id,key,filename,size,content_type,uploaded_at,metadata,is_public,description,uploaded_by_id
0,3,downloads/printserver/DashPrintServer-1.0.0-20250819.zip,DashPrintServer-1.0.0-20250819.zip,11693,application/zip,2025-08-19 01:11:50.654206+00:00,"{'version': '1.0.0-20250819', 'changelog': 'Print server release 1.0.0-20250819', 'file_type': 'print_server_release...",False,EcoThrift Print Server v1.0.0-20250819,NaN
1,4,downloads/printserver/EcoThrift_PrintServer_v2.1.zip,EcoThrift_PrintServer_v2.1.zip,84923,application/zip,2025-08-19 20:33:31.997682+00:00,"{'version': '2.1', 'features': ['QR Code support', 'Hierarchical typography', 'Custom logo branding', 'Portrait orie...",False,EcoThrift Print Server v2.1 - Enhanced QR Code Labels,NaN
2,5,manifests/2025/08/PO_WAL135287_20250822_183204.csv,wal8240-077-07-25-25.csv,163840,text/csv,2025-08-22 18:32:04.511316+00:00,"{'row_count': '846', 'upload_user': 'retag_user', 'header_count': '11', 'purchase_order_id': '3'}",False,,3.0

======================================================================
  core_user  (39 rows)
======================================================================

Columns:

                       column_name                 data_type is_nullable column_default
0                               id                    bigint          NO           None
1                         password         character varying          NO           None
2                       last_login  timestamp with time zone         YES           None
3                     is_superuser                   boolean          NO           None
4                            email         character varying          NO           None
5                         username         character varying          NO           None
6                       first_name         character varying          NO           None
7                        last_name         character varying          NO           None
8                      middle_name         character varying          NO           None
9                            phone         character varying          NO           None
10                      birth_date                      date         YES           None
11                     is_employee                   boolean          NO           None
12                     is_customer                   boolean          NO           None
13                       is_active                   boolean          NO           None
14                        is_staff                   boolean          NO           None
15                     date_joined  timestamp with time zone          NO           None
16                      updated_at  timestamp with time zone          NO           None
17          emergency_contact_name         character varying          NO           None
18         emergency_contact_phone         character varying          NO           None
19  emergency_contact_relationship         character varying          NO           None
20                work_location_id                    bigint         YES           None

Foreign keys:

        column_name            fk_table fk_column
0  work_location_id  core_work_location        id

Sample (3 rows):

,id,password,last_login,is_superuser,email,username,first_name,last_name,middle_name,phone,birth_date,is_employee,is_customer,is_active,is_staff,date_joined,updated_at,emergency_contact_name,emergency_contact_phone,emergency_contact_relationship,work_location_id
0,5,pbkdf2_sha256$1000000$mat79d1GkxqPVgwv6uULOG$eNXF4yyolyzj0cQUQ/W9xHk+G/PMsJ/wJQ553cTA6Sc=,None,False,liveswords@yahoo.com,EMP25002,Kass,Ayala,,(402) 689-7481,None,True,False,True,False,2025-08-26 20:41:04.593910+00:00,2025-08-26 20:41:04.593910+00:00,Megan Martin,(618) 373-3946,Emergency Contact,None
1,7,pbkdf2_sha256$1000000$mat79d1GkxqPVgwv6uULOG$eNXF4yyolyzj0cQUQ/W9xHk+G/PMsJ/wJQ553cTA6Sc=,None,False,rlkilduff@gmail.com,EMP25004,Richard,Kilduff,,(531) 255-3048,None,True,False,True,False,2025-08-26 20:41:04.593910+00:00,2025-08-26 20:41:04.593910+00:00,David Kilduff,(531) 213-9557,Emergency Contact,None
2,8,pbkdf2_sha256$1000000$mat79d1GkxqPVgwv6uULOG$eNXF4yyolyzj0cQUQ/W9xHk+G/PMsJ/wJQ553cTA6Sc=,None,False,elijahjacksonnash@gmail.com,EMP25005,Elijah,Jackson-Nash,,(531) 777-4793,None,True,False,True,False,2025-08-26 20:41:04.593910+00:00,2025-08-26 20:41:04.593910+00:00,,,,None

======================================================================
  core_user_groups  (48 rows)
======================================================================

Columns:

  column_name data_type is_nullable column_default
0          id    bigint          NO           None
1     user_id    bigint          NO           None
2    group_id   integer          NO           None

Foreign keys:

  column_name    fk_table fk_column
0    group_id  auth_group        id
1     user_id   core_user        id

Sample (3 rows):

   id  user_id  group_id
0   1        1         1
1   2        1         2
2   4        3         8

======================================================================
  core_user_user_permissions  (0 rows)
======================================================================

Columns:

     column_name data_type is_nullable column_default
0             id    bigint          NO           None
1        user_id    bigint          NO           None
2  permission_id   integer          NO           None

Foreign keys:

     column_name         fk_table fk_column
0  permission_id  auth_permission        id
1        user_id        core_user        id

======================================================================
  core_work_location  (5 rows)
======================================================================

Columns:

       column_name                 data_type is_nullable column_default
0               id                    bigint          NO           None
1             name         character varying          NO           None
2             code         character varying          NO           None
3    location_type         character varying          NO           None
4        is_active                   boolean          NO           None
5       created_at  timestamp with time zone          NO           None
6       updated_at  timestamp with time zone          NO           None
7       address_id                    bigint          NO           None
8      theme_color         character varying          NO           None
9   gradient_start         character varying          NO           None
10    gradient_end         character varying          NO           None

Foreign keys:

  column_name      fk_table fk_column
0  address_id  core_address        id

Sample (3 rows):

   id              name  code location_type  is_active                       created_at                       updated_at  address_id theme_color gradient_start gradient_end
0   1       Warehouse 1   WH1     warehouse       True 2025-08-19 21:14:23.831337+00:00 2025-08-19 21:14:23.831352+00:00           1     #000000        #000000      #000000
1   2       Warehouse 2   WH2     warehouse       True 2025-08-19 21:14:23.839698+00:00 2025-08-19 21:14:23.839710+00:00           2     #000000        #000000      #000000
2   3  Corporate Office  CORP        office       True 2025-08-19 21:14:23.846495+00:00 2025-08-19 21:14:23.846502+00:00           3     #000000        #000000      #000000

## 1D — DB2 Date ranges & counts

In [6]:
db2_stats_sql = text("""
SELECT
    -- Items
    (SELECT COUNT(*) FROM inventory_item)                                           AS total_items,
    (SELECT COUNT(*) FROM inventory_item WHERE sold_at IS NOT NULL)                 AS sold_items,
    (SELECT COUNT(*) FROM inventory_item WHERE sold_at >= '2025-01-01')             AS sold_since_2025,
    (SELECT COUNT(*) FROM inventory_item WHERE sold_at >= NOW() - INTERVAL '16 months') AS sold_last_16mo,
    (SELECT MIN(sold_at) FROM inventory_item WHERE sold_at IS NOT NULL)             AS earliest_sale,
    (SELECT MAX(sold_at) FROM inventory_item WHERE sold_at IS NOT NULL)             AS latest_sale,
    -- Products
    (SELECT COUNT(*) FROM inventory_product)                                        AS total_products,
    -- Date range of all items
    (SELECT MIN(created_on) FROM inventory_item)                                    AS earliest_item_created,
    (SELECT MAX(created_on) FROM inventory_item)                                    AS latest_item_created
""")

# created_on might not exist — fall back to id ordering
try:
    with eng2.connect() as conn:
        df_db2_stats = pd.read_sql_query(db2_stats_sql, conn)
    print("=== DB2 Key Stats ===")
    display(df_db2_stats.T.rename(columns={0: "value"}))
except Exception as e:
    print(f"Stats query error (column name issue?): {e}")
    # Simpler fallback
    fallback = text("""
    SELECT
        (SELECT COUNT(*) FROM inventory_item) AS total_items,
        (SELECT COUNT(*) FROM inventory_item WHERE sold_at IS NOT NULL) AS sold_items,
        (SELECT COUNT(*) FROM inventory_item WHERE sold_at >= '2025-01-01') AS sold_since_2025,
        (SELECT COUNT(*) FROM inventory_item WHERE sold_at >= NOW() - INTERVAL '16 months') AS sold_last_16mo,
        (SELECT MIN(sold_at) FROM inventory_item WHERE sold_at IS NOT NULL) AS earliest_sale,
        (SELECT MAX(sold_at) FROM inventory_item WHERE sold_at IS NOT NULL) AS latest_sale,
        (SELECT COUNT(*) FROM inventory_product) AS total_products
    """)
    with eng2.connect() as conn:
        df_db2_stats = pd.read_sql_query(fallback, conn)
    print("=== DB2 Key Stats (fallback) ===")
    display(df_db2_stats.T.rename(columns={0: "value"}))

Stats query error (column name issue?): Execution failed on sql '
SELECT
    -- Items
    (SELECT COUNT(*) FROM inventory_item)                                           AS total_items,
    (SELECT COUNT(*) FROM inventory_item WHERE sold_at IS NOT NULL)                 AS sold_items,
    (SELECT COUNT(*) FROM inventory_item WHERE sold_at >= '2025-01-01')             AS sold_since_2025,
    (SELECT COUNT(*) FROM inventory_item WHERE sold_at >= NOW() - INTERVAL '16 months') AS sold_last_16mo,
    (SELECT MIN(sold_at) FROM inventory_item WHERE sold_at IS NOT NULL)             AS earliest_sale,
    (SELECT MAX(sold_at) FROM inventory_item WHERE sold_at IS NOT NULL)             AS latest_sale,
    -- Products
    (SELECT COUNT(*) FROM inventory_product)                                        AS total_products,
    -- Date range of all items
    (SELECT MIN(created_on) FROM inventory_item)                                    AS earliest_item_created,
    (SELECT MAX(created_on) FROM inventory_item)                                    AS latest_item_created
': (psycopg2.errors.UndefinedColumn) column "created_on" does not exist
LINE 13:     (SELECT MIN(created_on) FROM inventory_item)            ...
                         ^
HINT:  Perhaps you meant to reference the column "inventory_item.created_at".

[SQL:
SELECT
    -- Items
    (SELECT COUNT(*) FROM inventory_item)                                           AS total_items,
    (SELECT COUNT(*) FROM inventory_item WHERE sold_at IS NOT NULL)                 AS sold_items,
    (SELECT COUNT(*) FROM inventory_item WHERE sold_at >= '2025-01-01')             AS sold_since_2025,
    (SELECT COUNT(*) FROM inventory_item WHERE sold_at >= NOW() - INTERVAL '16 months') AS sold_last_16mo,
    (SELECT MIN(sold_at) FROM inventory_item WHERE sold_at IS NOT NULL)             AS earliest_sale,
    (SELECT MAX(sold_at) FROM inventory_item WHERE sold_at IS NOT NULL)             AS latest_sale,
    -- Products
    (SELECT COUNT(*) FROM inventory_product)                                        AS total_products,
    -- Date range of all items
    (SELECT MIN(created_on) FROM inventory_item)                                    AS earliest_item_created,
    (SELECT MAX(created_on) FROM inventory_item)                                    AS latest_item_created
]
(Background on this error at: https://sqlalche.me/e/20/f405)
=== DB2 Key Stats (fallback) ===

                                            value
total_items                                 59833
sold_items                                  34762
sold_since_2025                             34762
sold_last_16mo                              34762
earliest_sale    2025-08-23 15:11:11.629839+00:00
latest_sale      2026-03-04 18:16:58.698128+00:00
total_products                              41509

## 1E — DB2 Category deep-dive
Shows all category-related columns on product, plus the full `inventory_category` table if it exists.

In [7]:
ip_cols = db2_schemas.get("inventory_product", {}).get("cols", set())
cat_cols_db2 = sorted(c for c in ip_cols if any(k in c.lower() for k in ["categ", "sub", "type", "class", "dept"]))
print("inventory_product category-related columns:", cat_cols_db2)

for col in cat_cols_db2:
    sql = text(f'SELECT "{col}"::text AS val, COUNT(*) AS cnt FROM inventory_product GROUP BY 1 ORDER BY cnt DESC LIMIT 40')
    with eng2.connect() as conn:
        df_vals = pd.read_sql_query(sql, conn)
    print(f"\nDistinct values — inventory_product.{col} (top 40):")
    display(df_vals)

if table_exists(eng2, "inventory_category", sch2):
    sql_all_cats = text("SELECT * FROM inventory_category ORDER BY id")
    with eng2.connect() as conn:
        df_cats = pd.read_sql_query(sql_all_cats, conn)
    print(f"\nFull inventory_category table ({len(df_cats)} rows):")
    display(df_cats)
else:
    print("\ninventory_category table does not exist in DB2.")

inventory_product category-related columns: ['product_class_id']

Distinct values — inventory_product.product_class_id (top 40):

    val    cnt
0  None  41509

inventory_category table does not exist in DB2.

## 1F — DB2 Purchase Order stats

In [8]:
po_table = None
for candidate in ["inventory_purchaseorder", "inventory_purchase_order", "purchase_order"]:
    if candidate in db2_schemas:
        po_table = candidate
        break

if po_table:
    po_cols = db2_schemas[po_table]["cols"]
    # Try to find date columns
    date_cols = sorted(c for c in po_cols if any(k in c.lower() for k in ["date", "created", "ordered", "time"]))
    print(f"PO table: {po_table} ({db2_schemas[po_table]['n']} rows)")
    print(f"Date columns: {date_cols}")
    # Show distinct statuses if status column exists
    for col in ["status", "order_status"]:
        if col in po_cols:
            sql = text(f'SELECT "{col}", COUNT(*) AS cnt FROM "{po_table}" GROUP BY 1 ORDER BY cnt DESC')
            with eng2.connect() as conn:
                display(pd.read_sql_query(sql, conn))
else:
    print("No purchase order table found in DB2.")

# Manifest / CSV template tables
for t in ["inventory_manifest", "inventory_manifestrow", "inventory_csv_template", "inventory_csvtemplate",
          "inventory_csv_field_mapping", "inventory_csvfieldmapping", "core_manifest"]:
    if t in db2_schemas:
        print(f"\n{t}: {db2_schemas[t]['n']} rows")

PO table: inventory_purchase_order (103 rows)
Date columns: ['created_at', 'created_by_id', 'purchase_date', 'received_date', 'updated_at']

            status  cnt
0  items_generated   62
1         received   40
2        confirmed    1

inventory_csv_template: 10 rows

inventory_csv_field_mapping: 120 rows

core_manifest: 0 rows

---
# PART 2 — DB1 (Old Production)
1st-generation app. Tables are unprefixed: `item`, `product`, `cart`, `cart_line`, `purchase_order`, `manifest`, etc.

In [9]:
eng1, sch1, lab1 = open_connection("old_production")
print(f"Connected: {lab1}")

all_db1 = sorted(inspect(eng1).get_table_names(schema=sch1))
print(f"\nAll tables ({len(all_db1)}):")
for t in all_db1:
    print(f"  {t}")

Connected: DB1 — Old Production (archive)

All tables (58):
  accounts_profile
  address
  area
  auth_group
  auth_group_permissions
  auth_permission
  auth_user
  auth_user_groups
  auth_user_user_permissions
  cart
  cart_discount
  cart_line
  data_value
  department
  department_budget
  discount
  django_admin_log
  django_content_type
  django_migrations
  django_session
  drawer
  ecothrift_holidays
  employee
  employee_availability
  employee_compensation
  employee_departments
  giftcard
  item
  item_condition
  item_destination
  item_dispatch
  item_location
  item_status
  item_test_result
  list_condition
  list_status
  location
  manifest
  pay_period
  pay_week
  payment
  payroll_history
  permissions
  person
  price
  price_index
  product
  product_attrs
  purchase_order
  requests_off
  schedule
  shift
  standard_bogo
  thrift_plus
  thrift_plus_payment
  timeclock
  timeclock_entry
  v_price_label

## 2A — DB1 Inventory tables
`item`, `product`, `product_attrs`, and anything with categ/condition/status/location in the name.

In [10]:
inv_keywords = ["item", "product", "categ", "condition", "status", "location", "price", "manifest"]
db1_inv_tables = [t for t in all_db1 if any(k in t.lower() for k in inv_keywords)]
print("Inventory-related tables:", db1_inv_tables)

db1_schemas = {}
for t in db1_inv_tables:
    cols_df, n = full_describe(eng1, t, sch1, sample_n=3)
    db1_schemas[t] = {"cols": set(cols_df["column_name"]), "n": n}

Inventory-related tables: ['item', 'item_condition', 'item_destination', 'item_dispatch', 'item_location', 'item_status', 'item_test_result', 'list_condition', 'list_status', 'location', 'manifest', 'price', 'price_index', 'product', 'product_attrs', 'v_price_label']

======================================================================
  item  (123,941 rows)
======================================================================

Columns:

           column_name          data_type is_nullable                    column_default
0                   id            integer          NO  nextval('item_id_seq'::regclass)
1                 code          character         YES   create_table_code('item'::text)
2             bulk_cde          character         YES                               NaN
3             quantity            integer         YES                                 1
4         order_number               text         YES                               NaN
5          line_number            integer         YES                               NaN
6          product_cde          character         YES                               NaN
7            price_lbl  character varying         YES                               NaN
8           retail_amt            numeric         YES                               NaN
9   starting_price_amt            numeric         YES                               NaN
10           is_static            boolean         YES                             false

Sample (3 rows):

    id       code   bulk_cde  quantity order_number  line_number product_cde price_lbl  retail_amt  starting_price_amt  is_static
0  586  8LvknXmkx                    1    TGT100653          136   SMipQ17AY        Z6       35.00               26.25      False
1   13  jNZeWeGtR        NaN         1     AMZ11175           13   xwzLvOj3L       NaN       38.84               36.90      False
2   25  0LkGzcZDG        NaN         1     AMZ11175           25   ndCCDyLLn        A1       34.99               33.24      False

======================================================================
  item_condition  (130,112 rows)
======================================================================

Columns:

    column_name                 data_type is_nullable                              column_default
0            id                   integer          NO  nextval('item_condition_id_seq'::regclass)
1      item_cde                 character         YES                                         NaN
2  employee_cde                 character         YES                                         NaN
3  condition_id                   integer         YES                                         NaN
4         as_of  timestamp with time zone         YES                           CURRENT_TIMESTAMP

Sample (3 rows):

   id   item_cde employee_cde  condition_id                            as_of
0   1  qthFHRXwu    tjneVzTE8             3 2024-03-14 18:01:54.541820+00:00
1   2  k2O1NIkea    tjneVzTE8             3 2024-03-14 18:01:54.541820+00:00
2   3  JIYMLpYwL    tjneVzTE8             3 2024-03-14 18:01:54.541820+00:00

======================================================================
  item_destination  (130,108 rows)
======================================================================

Columns:

     column_name                 data_type is_nullable                                column_default
0             id                   integer          NO  nextval('item_destination_id_seq'::regclass)
1       item_cde                 character         YES                                           NaN
2   employee_cde                 character         YES                                           NaN
3  department_id                   integer         YES                                           NaN
4          notes                      text         YES                                      ''::text
5          as_of  timestamp with time zone         YES                             CURRENT_TIMESTAMP

Sample (3 rows):

   id   item_cde employee_cde  department_id notes                            as_of
0   1  qthFHRXwu    tjneVzTE8              1       2024-03-14 18:01:55.801971+00:00
1   2  k2O1NIkea    tjneVzTE8              1       2024-03-14 18:01:55.801971+00:00
2   3  JIYMLpYwL    tjneVzTE8              1       2024-03-14 18:01:55.801971+00:00

======================================================================
  item_dispatch  (89,736 rows)
======================================================================

Columns:

     column_name                 data_type is_nullable                             column_default
0             id                   integer          NO  nextval('item_dispatch_id_seq'::regclass)
1       item_cde                 character         YES                                        NaN
2   employee_cde                 character         YES                                        NaN
3  department_id                   integer         YES                                        NaN
4          notes                      text         YES                                   ''::text
5          as_of  timestamp with time zone         YES                          CURRENT_TIMESTAMP

Sample (3 rows):

   id   item_cde employee_cde  department_id notes                            as_of
0   1  tQU3eijW3    tjneVzTE8            3.0       2024-03-15 20:16:48.082937+00:00
1   2  tQU3eijW3    tjneVzTE8            NaN       2024-03-15 20:17:17.103244+00:00
2   3  tQU3eijW3    tjneVzTE8            1.0       2024-03-15 22:01:45.017094+00:00

======================================================================
  item_location  (0 rows)
======================================================================

Columns:

    column_name                 data_type is_nullable                             column_default
0            id                   integer          NO  nextval('item_location_id_seq'::regclass)
1      item_cde                 character         YES                                        NaN
2  employee_cde                 character         YES                                        NaN
3   location_id                   integer         YES                                        NaN
4         as_of  timestamp with time zone         YES                          CURRENT_TIMESTAMP

======================================================================
  item_status  (217,305 rows)
======================================================================

Columns:

    column_name                 data_type is_nullable                           column_default
0            id                   integer          NO  nextval('item_status_id_seq'::regclass)
1      item_cde                 character         YES                                      NaN
2  employee_cde                 character         YES                                      NaN
3     status_id                   integer         YES                                      NaN
4         as_of  timestamp with time zone         YES                        CURRENT_TIMESTAMP

Sample (3 rows):

   id   item_cde employee_cde  status_id                            as_of
0   1  qthFHRXwu    tjneVzTE8          1 2024-03-14 18:01:55.035973+00:00
1   2  k2O1NIkea    tjneVzTE8          1 2024-03-14 18:01:55.035973+00:00
2   3  JIYMLpYwL    tjneVzTE8          1 2024-03-14 18:01:55.035973+00:00

======================================================================
  item_test_result  (0 rows)
======================================================================

Columns:

     column_name                 data_type is_nullable                                column_default
0             id                   integer          NO  nextval('item_test_result_id_seq'::regclass)
1       item_cde         character varying         YES                                           NaN
2    as_is_value                   numeric         YES                                           NaN
3   repair_value                   numeric         YES                                           NaN
4  salvage_value                   numeric         YES                                           NaN
5       decision                      text         YES                                           NaN
6          notes                      text         YES                                           NaN
7          as_of  timestamp with time zone         YES                             CURRENT_TIMESTAMP

======================================================================
  list_condition  (7 rows)
======================================================================

Columns:

      column_name          data_type is_nullable                              column_default
0              id            integer          NO  nextval('list_condition_id_seq'::regclass)
1  condition_name  character varying         YES                                         NaN

Sample (3 rows):

   id condition_name
0   1            New
1   2       Like New
2   3      Very Good

======================================================================
  list_status  (27 rows)
======================================================================

Columns:

   column_name          data_type is_nullable                           column_default
0           id            integer          NO  nextval('list_status_id_seq'::regclass)
1  status_name  character varying         YES                                      NaN

Sample (3 rows):

   id               status_name
0   1    PreProcess - Purchased
1   2  PreProcess - Unfulfilled
2   3  PreProcess - Undelivered

======================================================================
  location  (0 rows)
======================================================================

Columns:

          column_name          data_type is_nullable                         column_default
0                  id            integer          NO  nextval('location_id_seq1'::regclass)
1  parent_location_id            integer         YES                                    NaN
2          address_id            integer         YES                                    NaN
3             type_id            integer          NO                                    NaN
4                code  character varying          NO                                    NaN
5                name  character varying         YES                                    NaN
6           is_active            boolean         YES                                   true

Foreign keys:

          column_name    fk_table fk_column
0          address_id     address        id
1  parent_location_id    location        id
2             type_id  data_value        id

======================================================================
  manifest  (107,748 rows)
======================================================================

Columns:

        column_name          data_type is_nullable                        column_default
0                id            integer          NO  nextval('manifest_id_seq'::regclass)
1      order_number               text         YES                                   NaN
2       line_number            integer         YES                                   NaN
3          quantity            integer         YES                                   NaN
4        retail_amt            numeric         YES                                   NaN
5    ext_retail_amt            numeric         YES                                   NaN
6       description               text         YES                                   NaN
7             brand               text         YES                                   NaN
8             model               text         YES                                   NaN
9          category               text         YES                                   NaN
10      subcategory               text         YES                                   NaN
11        pallet_id               text         YES                                   NaN
12              upc               text         YES                                   NaN
13              sku               text         YES                                   NaN
14  search_string_1               text         YES                                   NaN
15  search_string_2               text         YES                                   NaN
16  search_string_3               text         YES                                   NaN
17      product_cde  character varying         YES               NULL::character varying

Sample (3 rows):

,id,order_number,line_number,quantity,retail_amt,ext_retail_amt,description,brand,model,category,subcategory,pallet_id,upc,sku,search_string_1,search_string_2,search_string_3,product_cde
0,101336,AMZ32833,48,1,73.38,73.38,"Master Equipment Pet Grooming Table For Pets,Blue",Master Equipment,,Grooming,Grooming Tools,LIQ:3PL:PALLET:LNRM:PAL23652,5231622281,B001VPAEQS,3PLLIQ:3PL:PALLET:LNRM:PAL2365212,523160022281.0,LPNNH4BW1MFT1,QkFQZnXut
1,101513,AMZ32833,225,1,34.99,34.99,"Arm & Hammer Platinum Slide Easy Clean, Clumping Litter, Multicat, 37 Lbs",Arm & Hammer,,Litter & Odor,Litter,LIQ:3PL:PALLET:LNRM:PAL26489,3321867,B07GL8SLKY,3PLLIQ:3PL:PALLET:LNRM:PAL264894,33200001867.0,LPNNA5SZ98BJM,J6A9dm8OP
2,101621,AMZ32833,333,1,27.99,27.99,"Kitty Sift (6Pack) Disposable Cat Litter Box, Sustainable, Clean Jumbo, 6Pack",Kitty Sift,,Litter & Odor,Litter,LIQ:3PL:PALLET:LNRM:PAL27044,852973419,B0B172YS7C,3PLLIQ:3PL:PALLET:LNRM:PAL2704418,850029734109.0,LPNNH4YCJHT43,55AzpdInK

======================================================================
  price  (10,816 rows)
======================================================================

Columns:

     column_name          data_type is_nullable                     column_default
0             id            integer          NO  nextval('price_id_seq'::regclass)
1           code  character varying         YES                                NaN
2       week_num            integer         YES                                NaN
3         amount            numeric         YES                                NaN
4  weeks_to_zero            integer         YES                                NaN

Sample (3 rows):

   id code  week_num   amount  weeks_to_zero
0   1   A4         0  50000.0            104
1   2   B4         0  47000.0            103
2   3   C4         0  44000.0            102

======================================================================
  price_index  (234 rows)
======================================================================

Columns:

  column_name          data_type is_nullable column_default
0       index            integer          NO           None
1        code  character varying          NO           None
2      amount            numeric          NO           None
3       label  character varying          NO           None

Sample (3 rows):

   index code  amount  label
0    233   A1     0.0   Free
1    232   A2     0.0   Free
2    231   A3     0.0   Free

======================================================================
  product  (140,621 rows)
======================================================================

Columns:

  column_name  data_type is_nullable                       column_default
0          id    integer          NO  nextval('product_id_seq'::regclass)
1        code  character         YES   create_table_code('product'::text)
2       title       text         YES                                  NaN
3       brand       text         YES                                  NaN
4       model       text         YES                                  NaN

Sample (3 rows):

      id       code                                                   title                             brand                     model
0  48781  UOfuqdqLL              D&D Player's Handbook - 2024 Core Rulebook                Dungeons & Dragons  D&D Players Handbook2024
1  49294  5bXhDwsFp  Twin/Twin XL Cotton Percale Fitted Sheet - Icon Yellow  Opalhouse Designed With Jungalow
2  51443  l27TZGxxe            Glass Dinner Plates - 10.7in, White, 6pc Set                    Made By Design

======================================================================
  product_attrs  (152,983 rows)
======================================================================

Columns:

     column_name                 data_type is_nullable                             column_default
0             id                   integer          NO  nextval('product_attrs_id_seq'::regclass)
1    product_cde                 character         YES                                        NaN
2            upc                      text         YES                                        NaN
3       category                      text         YES                                        NaN
4    subcategory                      text         YES                                        NaN
5     retail_amt                   numeric         YES                                        NaN
6          attrs                      text         YES                                        NaN
7       quantity                   integer         YES                                        NaN
8  last_instance  timestamp with time zone         YES                                 get_time()
9        taxable                   boolean          NO                                       true

Sample (3 rows):

   id product_cde            upc      category  subcategory  retail_amt attrs  quantity                    last_instance  taxable
0   1   mksNtyUkK  8939865242886  Home & Decor  Kitchenware      169.95  None         1 2024-03-14 13:01:52.825979+00:00     True
1   2   mKX9OKzMV    61124738833  Home & Decor   Appliances       89.00  None         1 2024-03-14 13:01:52.825979+00:00     True
2   3   QZCKFL04a     6285435218  Home & Decor  Kitchenware       84.38  None         1 2024-03-14 13:01:52.825979+00:00     True

======================================================================
  v_price_label  (190 rows)
======================================================================

Columns:

         column_name data_type is_nullable column_default
0  price_dynamic_lbl      text         YES           None

Sample (3 rows):

  price_dynamic_lbl
0                U9
1                V1
2                V2

## 2B — DB1 Sales tables
`cart`, `cart_line`, `payment`, `discount`, `giftcard`, `drawer`.

In [11]:
sales_keywords = ["cart", "payment", "discount", "giftcard", "drawer", "sale", "transaction"]
db1_sales_tables = [t for t in all_db1 if any(k in t.lower() for k in sales_keywords) and t not in db1_schemas]
print("Sales-related tables:", db1_sales_tables)

for t in db1_sales_tables:
    cols_df, n = full_describe(eng1, t, sch1, sample_n=3)
    db1_schemas[t] = {"cols": set(cols_df["column_name"]), "n": n}

Sales-related tables: ['cart', 'cart_discount', 'cart_line', 'discount', 'drawer', 'giftcard', 'payment', 'thrift_plus_payment']

======================================================================
  cart  (53,304 rows)
======================================================================

Columns:

              column_name                 data_type is_nullable                    column_default
0                      id                   integer          NO  nextval('cart_id_seq'::regclass)
1                    code         character varying         YES                               NaN
2              drawer_cde         character varying         YES                               NaN
3               open_time  timestamp with time zone         YES                               NaN
4              close_time  timestamp with time zone         YES                               NaN
5            subtotal_amt                   numeric         YES                               NaN
6      total_discount_amt                   numeric         YES                               NaN
7       total_taxable_amt                   numeric         YES                               NaN
8    sales_tax_percentage                   numeric         YES                               NaN
9                 tax_amt                   numeric         YES                               NaN
10              total_amt                   numeric         YES                               NaN
11      total_payment_amt                   numeric         YES                               NaN
12                  notes                      text         YES                               NaN
13                   void                   boolean         YES                             false
14            void_reason                      text         YES                               NaN
15      replaced_cart_cde         character varying         YES                               NaN
16  thrift_plus_member_id                   integer         YES                               NaN

Sample (3 rows):

,id,code,drawer_cde,open_time,close_time,subtotal_amt,total_discount_amt,total_taxable_amt,sales_tax_percentage,tax_amt,total_amt,total_payment_amt,notes,void,void_reason,replaced_cart_cde,thrift_plus_member_id
0,34265,1RB3U2OQj,w3FzPYBHi,2024-02-25 10:20:45-06:00,2024-02-25 10:39:59-06:00,11.0,0.0,11.0,7.0,0.77,11.77,20.0,,False,,None,None
1,31176,lsI8SvUet,yLiDObHf0,2023-12-15 07:29:30-06:00,2023-12-15 07:31:09-06:00,10.0,0.0,10.0,7.0,0.70,10.70,10.7,,False,,None,None
2,29486,43f67j1Cb,nfzCX4Nvv,2023-09-27 09:07:39-05:00,2023-09-27 09:26:48-05:00,4.0,0.0,4.0,7.0,0.28,4.28,4.5,NaN,False,NaN,None,None

======================================================================
  cart_discount  (1,505 rows)
======================================================================

Columns:

    column_name          data_type is_nullable                             column_default
0            id            integer          NO  nextval('cart_discount_id_seq'::regclass)
1      cart_cde  character varying         YES                                        NaN
2  discount_cde  character varying         YES                                        NaN
3    cart_label               text         YES                                        NaN
4    cart_value            numeric         YES                                        NaN
5       taxable            boolean         YES                                       true

Sample (3 rows):

   id   cart_cde discount_cde                 cart_label  cart_value  taxable
0   3  700fskKoY    99OFFSALE  99% OFF SALE - -0.16% OFF        0.00     True
1   4  bobl3OZHj    99OFFSALE  99% OFF SALE - -0.15% OFF        0.00     True
2   5  nXyWIBpH7    99OFFSALE   99% OFF SALE - 0.49% OFF       -0.13     True

======================================================================
  cart_line  (173,475 rows)
======================================================================

Columns:

        column_name          data_type is_nullable                         column_default
0                id            integer          NO  nextval('cart_line_id_seq'::regclass)
1          cart_cde  character varying         YES                                    NaN
2          item_cde  character varying         YES                                    NaN
3          line_num            integer         YES                                    NaN
4  line_description               text         YES                                    NaN
5          quantity            integer         YES                                    NaN
6    unit_price_amt            numeric         YES                                    NaN
7   total_price_amt            numeric         YES                                    NaN
8           taxable            boolean         YES                                   true
9  is_standard_bogo            boolean         YES                                  false

Sample (3 rows):

      id   cart_cde   item_cde  line_num                               line_description  quantity  unit_price_amt  total_price_amt  taxable  is_standard_bogo
0  66739  fNm6VXb95  kmb1cKvpz         2                         Meguiars Glass Cleaner         1             3.0              3.0     True             False
1  66740  fNyGtPmyt  gwV1Be32n         1                                   Unknown Item         1            51.0             51.0     True             False
2  66741  fP34cnpMa  HkAW2tf5h         1  Hillsville Patio Loveseat - White - Threshold         1           180.0            180.0     True             False

======================================================================
  discount  (3 rows)
======================================================================

Columns:

      column_name          data_type is_nullable                        column_default
0              id            integer          NO  nextval('discount_id_seq'::regclass)
1            code  character varying          NO                                   NaN
2           label  character varying          NO                                   NaN
3   discount_type  character varying          NO                                   NaN
4         value_1            numeric         YES                                   NaN
5         value_2            numeric         YES                                   NaN
6         value_3            numeric         YES                                   NaN
7         value_4            numeric         YES                                   NaN
8   product_codes  character varying         YES                                   NaN
9      extra_data  character varying         YES                                   NaN
10  is_combinable            boolean          NO                                 false
11     valid_from               date          NO                          CURRENT_DATE
12       valid_to               date          NO                                   NaN

Sample (3 rows):

   id       code                                    label discount_type  value_1  value_2  value_3  value_4 product_codes extra_data  is_combinable  valid_from    valid_to
0   1  BGO241015            BOGO - Direct Mailer 10.15.24      BOGO_ANY    200.0      NaN      NaN      NaN          None       None          False  2024-09-22  2024-10-15
1   2  SPD241015  When you spend - Direct Mailer 10.15.24        TIERED     50.0      5.0    100.0     15.0          None       None          False  2024-09-22  2024-10-15
2   3  10P241015         10% Off - Direct Mailer 10.15.24    PERCENTAGE     10.0      NaN      NaN      NaN          None       None          False  2024-09-22  2024-10-15

======================================================================
  drawer  (918 rows)
======================================================================

Columns:

         column_name                 data_type is_nullable                      column_default
0                 id                   integer          NO  nextval('drawer_id_seq'::regclass)
1               code         character varying         YES                                 NaN
2        cashier_cde         character varying         YES                                 NaN
3   open_manager_cde         character varying         YES                                 NaN
4  close_manager_cde         character varying         YES                                 NaN
5          open_time  timestamp with time zone         YES                                 NaN
6         close_time  timestamp with time zone         YES                                 NaN
7      open_cash_amt                   numeric         YES                                 NaN
8     close_cash_amt                   numeric         YES                                 NaN

Sample (3 rows):

    id       code cashier_cde open_manager_cde close_manager_cde                 open_time                close_time  open_cash_amt  close_cash_amt
0   30  yLiDObHf0   JMdvtuLWX                                    2023-12-15 08:56:41+00:00 1899-12-30 00:00:00+00:00          200.0            0.00
1  345  UVFQjxKPm   csGwneYMm                                    2023-12-22 08:41:03+00:00 1899-12-30 00:00:00+00:00          200.0            0.00
2   46  PC4CkRnTS   GGYCk4C6H        tjneVzTE8         tjneVzTE8 2023-02-24 11:27:52+00:00 2023-02-24 19:27:52+00:00          200.0          313.42

======================================================================
  giftcard  (31 rows)
======================================================================

Columns:

       column_name                 data_type is_nullable                        column_default
0               id                   integer          NO  nextval('giftcard_id_seq'::regclass)
1             code                 character         YES                                   NaN
2  original_amount                   numeric          NO                                     0
3          balance                   numeric          NO                                     0
4           status              USER-DEFINED          NO            'Created'::giftcard_status
5       updated_on  timestamp with time zone         YES                                 now()
6       created_on  timestamp with time zone         YES                                 now()

Sample (3 rows):

   id       code  original_amount  balance status                       updated_on                       created_on
0   4  KCFPjH4zO             10.0      0.0  Ready 2024-12-13 16:10:45.989563+00:00 2024-12-13 16:10:45.989563+00:00
1   5  ANzUWuGr4             10.0      0.0  Ready 2024-12-13 16:10:45.989563+00:00 2024-12-13 16:10:45.989563+00:00
2   6  VV2JyAl8n             10.0      0.0  Ready 2024-12-13 16:10:45.989563+00:00 2024-12-13 16:10:45.989563+00:00

======================================================================
  payment  (55,176 rows)
======================================================================

Columns:

    column_name          data_type is_nullable                       column_default
0            id            integer          NO  nextval('payment_id_seq'::regclass)
1      cart_cde  character varying          NO                                  NaN
2          type               text          NO                                  NaN
3        amount            numeric         YES                                  NaN
4    fee_amount            numeric         YES                                 0.00
5    pmt_string               text         YES                                  NaN
6  giftcard_cde  character varying         YES                                  NaN

Sample (3 rows):

      id   cart_cde    type  amount  fee_amount pmt_string giftcard_cde
0  29067  Hj1BtWsgK  Credit   10.97        0.27       None         None
1  29068  5rvt9ThKM  Credit   26.32        0.64       None         None
2  29069  YVpmHUuUf    Cash   60.00        0.00       None         None

======================================================================
  thrift_plus_payment  (4 rows)
======================================================================

Columns:

       column_name data_type is_nullable                                   column_default
0               id   integer          NO  nextval('thrift_plus_payment_id_seq'::regclass)
1        member_id   integer          NO                                              NaN
2          cart_id   integer         YES                                              NaN
3     payment_date      date         YES                                     CURRENT_DATE
4           amount   numeric         YES                                              NaN
5  duration_months   integer         YES                                              NaN
6       start_date      date         YES                                              NaN
7         end_date      date         YES                                              NaN

Foreign keys:

  column_name     fk_table  fk_column
0     cart_id         cart         id
1   member_id  thrift_plus  member_id

Sample (3 rows):

   id  member_id  cart_id payment_date  amount  duration_months  start_date    end_date
0   1  307300189    51552   2024-10-29   19.99                1  2024-10-29  2024-11-28
1   2  901761238    51553   2024-10-29   19.99                1  2024-10-29  2024-11-28
2   4  668738426    51609   2024-10-30   19.99                1  2024-10-30  2024-11-29

## 2C — DB1 Order / Vendor tables

In [12]:
order_keywords = ["order", "vendor", "purchase", "department"]
db1_order_tables = [t for t in all_db1 if any(k in t.lower() for k in order_keywords) and t not in db1_schemas]
print("Order-related tables:", db1_order_tables)

for t in db1_order_tables:
    cols_df, n = full_describe(eng1, t, sch1, sample_n=3)
    db1_schemas[t] = {"cols": set(cols_df["column_name"]), "n": n}

Order-related tables: ['department', 'department_budget', 'employee_departments', 'purchase_order']

======================================================================
  department  (8 rows)
======================================================================

Columns:

  column_name          data_type is_nullable                                      column_default
0          id            integer          NO  nextval('departments_department_id_seq'::regclass)
1        name  character varying          NO                                                 NaN
2  manager_id            integer         YES                                                 NaN

Foreign keys:

  column_name  fk_table fk_column
0  manager_id  employee        id

Sample (3 rows):

   id         name  manager_id
0   2    Warehouse           1
1   3  Restoration          72
2   4   Processing          10

======================================================================
  department_budget  (36 rows)
======================================================================

Columns:

      column_name                 data_type is_nullable                                 column_default
0              id                   integer          NO  nextval('department_budget_id_seq'::regclass)
1   department_id                   integer          NO                                            NaN
2  budget_type_id                   integer          NO                                            NaN
3      budget_amt                   numeric          NO                                            NaN
4  effective_date                      date          NO                                            NaN
5        end_date                      date         YES                             '9999-12-31'::date
6           notes                      text         YES                                            NaN
7      updated_on  timestamp with time zone          NO                              CURRENT_TIMESTAMP
8      updated_by                   integer          NO                                            NaN

Foreign keys:

       column_name    fk_table fk_column
0   budget_type_id  data_value        id
1    department_id  department        id
2    department_id  department        id
3    department_id  department        id
4    department_id  department        id
5    department_id  department        id
6    department_id  department        id
7    department_id  department        id
8    department_id  department        id
9    department_id  department        id
10   department_id  department        id
11   department_id  department        id
12   department_id  department        id
13   department_id  department        id
14   department_id  department        id
15   department_id  department        id
16   department_id  department        id
17   department_id  department        id
18   department_id  department        id
19   department_id  department        id
20   department_id  department        id
21   department_id  department        id
22   department_id  department        id
23   department_id  department        id
24   department_id  department        id
25   department_id  department        id
26   department_id  department        id
27   department_id  department        id
28   department_id  department        id
29   department_id  department        id
30   department_id  department        id
31   department_id  department        id
32   department_id  department        id
33   department_id  department        id
34   department_id  department        id
35   department_id  department        id
36   department_id  department        id
37      updated_by    employee        id
38      updated_by    employee        id
39      updated_by    employee        id
40      updated_by    employee        id

Sample (3 rows):

   id  department_id  budget_type_id  budget_amt effective_date    end_date                       notes                       updated_on  updated_by
0  19              1              35      2000.0     2025-01-01  9999-12-31  2025 Placeholder - Payroll 2024-09-01 19:58:25.153479+00:00           1
1  20              2              35      2000.0     2025-01-01  9999-12-31  2025 Placeholder - Payroll 2024-09-01 19:58:25.153479+00:00           1
2  21              3              35      2000.0     2025-01-01  9999-12-31  2025 Placeholder - Payroll 2024-09-01 19:58:25.153479+00:00           1

======================================================================
  employee_departments  (33 rows)
======================================================================

Columns:

     column_name data_type is_nullable column_default
0    employee_id   integer          NO           None
1  department_id   integer          NO           None

Foreign keys:

      column_name    fk_table fk_column
0   department_id  department        id
1   department_id  department        id
2   department_id  department        id
3   department_id  department        id
4   department_id  department        id
..            ...         ...       ...
80    employee_id    employee        id
81    employee_id    employee        id
82    employee_id    employee        id
83    employee_id    employee        id
84    employee_id    employee        id

[85 rows x 3 columns]

Sample (3 rows):

   employee_id  department_id
0           79              5
1           82              4
2            9              4

======================================================================
  purchase_order  (210 rows)
======================================================================

Columns:

             column_name                 data_type is_nullable                               column_default
0                     id                   integer          NO  nextval('purchase_order_id_seq1'::regclass)
1                 number                      text         YES                                          NaN
2             created_on  timestamp with time zone         YES                                   get_time()
3             retail_amt                   numeric         YES                                          NaN
4           condition_id                   integer         YES                                          NaN
5               quantity                   integer         YES                                          NaN
6            description                      text         YES                                          NaN
7              price_amt                   numeric         YES                                          NaN
8                fee_amt                   numeric         YES                                          NaN
9           shipping_amt                   numeric         YES                                          NaN
10              paid_amt                   numeric         YES                                          NaN
11  delivery_address_cde         character varying         YES               'WTx5czCwn'::character varying
12    scheduled_delivery  timestamp with time zone         YES                                          NaN
13           received_on  timestamp with time zone         YES                                          NaN
14          purchased_on  timestamp with time zone         YES                                          NaN
15               paid_on  timestamp with time zone         YES                                          NaN
16       preprocessed_on  timestamp with time zone         YES                                          NaN
17          processed_on  timestamp with time zone         YES                                          NaN

Sample (3 rows):

,id,number,created_on,retail_amt,condition_id,quantity,description,price_amt,fee_amt,shipping_amt,paid_amt,delivery_address_cde,scheduled_delivery,received_on,purchased_on,paid_on,preprocessed_on,processed_on
0,277,HMD64501,2025-04-29 00:00:00+00:00,93414.0,4,1348,"Truckload of Tools & Hardware, Stores Inventory, 1,348 Units, Ext. Retail $93,414, Atlanta, GA",17575.0,703.0,2225.95,20503.95,WTx5czCwn,2025-05-06 22:00:00+00:00,2025-05-05 17:00:00+00:00,2025-04-15 17:00:00+00:00,2025-04-22 17:00:00+00:00,2025-04-29 17:00:00+00:00,None
1,323,TGT127191,2025-06-17 15:10:15.455153+00:00,61371.0,4,1478,"Truckload (24 Pallets) of Bedding, Soft Décor, Lighting/Wall Décor & More, Used - Good Condition, 1,478 Units, Ext. ...",6950.0,278.0,1441.61,8669.61,WTx5czCwn,2025-06-19 13:00:00+00:00,2025-06-18 17:00:00+00:00,2025-06-04 17:00:00+00:00,2025-06-07 17:00:00+00:00,2025-06-08 17:00:00+00:00,None
2,327,WFR12437,2025-06-17 15:18:17.514587+00:00,73297.0,5,101,"Truckload of Bedroom, Outdoor, Kitchen & Dining Furniture & More, 101 Units, Retail $73,297, Used - Fair Condition, ...",4025.0,161.0,1328.74,5514.74,WTx5czCwn,2025-06-19 22:00:00+00:00,2025-06-19 17:00:00+00:00,2025-06-11 17:00:00+00:00,2025-06-12 17:00:00+00:00,2025-06-12 17:00:00+00:00,None

## 2D — DB1 Category deep-dive

In [13]:
# Product table categories
p_cols = db1_schemas.get("product", {}).get("cols", set())
cat_cols_db1 = sorted(c for c in p_cols if any(k in c.lower() for k in ["categ", "sub", "type", "class", "dept"]))
print("product category-related columns:", cat_cols_db1)

for col in cat_cols_db1:
    sql = text(f'SELECT "{col}"::text AS val, COUNT(*) AS cnt FROM product GROUP BY 1 ORDER BY cnt DESC LIMIT 40')
    with eng1.connect() as conn:
        df_vals = pd.read_sql_query(sql, conn)
    print(f"\nDistinct values — product.{col} (top 40):")
    display(df_vals)

# product_attrs categories
if "product_attrs" in db1_schemas:
    pa_cols = db1_schemas["product_attrs"]["cols"]
    cat_in_pa = sorted(c for c in pa_cols if any(k in c.lower() for k in ["categ", "sub", "type", "class", "dept"]))
    print(f"\nproduct_attrs category-related columns: {cat_in_pa}")
    for col in cat_in_pa:
        sql = text(f'SELECT "{col}"::text AS val, COUNT(*) AS cnt FROM product_attrs GROUP BY 1 ORDER BY cnt DESC LIMIT 40')
        with eng1.connect() as conn:
            df_vals = pd.read_sql_query(sql, conn)
        print(f"\nDistinct values — product_attrs.{col} (top 40):")
        display(df_vals)

product category-related columns: []

product_attrs category-related columns: ['category', 'subcategory']

Distinct values — product_attrs.category (top 40):

                               val    cnt
0                     Home & Decor  62805
1               Toys, Games & Arts  23461
2         Home Improvement & Tools  11169
3               Pets & Animal Care   9466
4   Beauty, Health & Personal Care   8521
5         Electronics & Technology   8293
6       Sports, Fitness & Outdoors   8123
7    Clothing, Shoes & Accessories   5257
8            Media & Entertainment   3959
9         Office & School Supplies   3099
10   Miscellaneous & Uncategorized   2903
11  Garden, Patio & Outdoor Living   2311
12             Automotive & Garage   1696
13                       Kids Home    603
14             Baby & Toddler Toys    166
15                  Bedding & Bath    123
16              Seasonal & Holiday    105
17           Kids' Bedding & Decor    100
18                   Baby Products     96
19             Party & Celebration     79
20           Kids' & Baby Clothing     77
21                             NaN     65
22                       Baby Care     64
23                            Baby     55
24             Musical Instruments     50
25                   Arts & Crafts     36
26              Arts, Toys & Games     33
27                  Bags & Luggage     30
28                  Nursery & Kids     23
29                     Baby & Kids     20
30                                     20
31                  Imaging-Office     19
32    Medical Supplies & Equipment     16
33                  Baby & Toddler     13
34       Baby, Toddler & Maternity     12
35          Baby, Kids & Maternity     10
36   Miscellaneous & Uncategorized      9
37                         Wayfair      8
38               Outdoor Furniture      7
39         Outdoor Power Equipment      7

Distinct values — product_attrs.subcategory (top 40):

                       val    cnt
0               Home Decor  13905
1              Kitchenware  13339
2           Bedding & Bath  13177
3   Storage & Organization  10989
4   Dolls & Action Figures   9039
5                     Dogs   6847
6               Appliances   4630
7                Furniture   4289
8          Games & Puzzles   3704
9     Phones & Accessories   3439
10           Personal Care   3324
11     Baby & Toddler Toys   3055
12                Hardware   2711
13      Seasonal & Holiday   2664
14      Outdoor Recreation   2585
15            Outdoor Play   2555
16           Arts & Crafts   2429
17             Team Sports   2342
18          Bags & Luggage   2311
19               Computers   2233
20     Party & Celebration   2144
21    Learning & Education   2101
22                    Cats   1720
23           Audio & Video   1667
24                Haircare   1614
25              Hand Tools   1560
26   Lighting & Electrical   1362
27             Power Tools   1329
28       Health & Wellness   1134
29    Organizational Tools   1133
30                Skincare   1132
31      Exercise Equipment   1085
32     Fitness Accessories   1063
33      Makeup & Cosmetics   1020
34  Car Care & Maintenance    864
35   Kids' & Baby Clothing    841
36             Accessories    811
37            Water Sports    783
38            Collectibles    686
39        Women's Clothing    643

## 2E — DB1 Date ranges & counts

In [14]:
db1_stats_sql = text("""
SELECT
    (SELECT COUNT(*) FROM item)                                                              AS total_items,
    (SELECT COUNT(DISTINCT i.code)
     FROM item i JOIN cart_line cl ON cl.item_cde = i.code
     JOIN cart c ON c.code = cl.cart_cde
     WHERE c.close_time IS NOT NULL AND c.void = false)                                      AS distinct_items_sold,
    (SELECT COUNT(*)
     FROM cart_line cl JOIN cart c ON c.code = cl.cart_cde
     WHERE c.close_time IS NOT NULL AND c.void = false)                                      AS total_sale_lines,
    (SELECT COUNT(*)
     FROM cart_line cl JOIN cart c ON c.code = cl.cart_cde
     WHERE c.close_time IS NOT NULL AND c.void = false
       AND c.close_time >= '2025-01-01')                                                     AS sale_lines_since_2025,
    (SELECT COUNT(*)
     FROM cart_line cl JOIN cart c ON c.code = cl.cart_cde
     WHERE c.close_time IS NOT NULL AND c.void = false
       AND c.close_time >= NOW() - INTERVAL '16 months')                                     AS sale_lines_last_16mo,
    (SELECT MIN(c.close_time) FROM cart c WHERE c.close_time IS NOT NULL AND c.void = false) AS earliest_sale,
    (SELECT MAX(c.close_time) FROM cart c WHERE c.close_time IS NOT NULL AND c.void = false) AS latest_sale,
    (SELECT COUNT(*) FROM product)                                                           AS total_products
""")

try:
    with eng1.connect() as conn:
        df_db1_stats = pd.read_sql_query(db1_stats_sql, conn)
    print("=== DB1 Key Stats ===")
    display(df_db1_stats.T.rename(columns={0: "value"}))
except Exception as e:
    print(f"Stats query error: {e}")
    print("Check column names against the item/cart schema above.")

=== DB1 Key Stats ===

                                           value
total_items                               123941
distinct_items_sold                        64058
total_sale_lines                          172868
sale_lines_since_2025                      78460
sale_lines_last_16mo                       90016
earliest_sale          2023-02-21 12:28:16+00:00
latest_sale            9999-12-31 00:00:00+00:00
total_products                            140621

---
# PART 3 — Summary

Compact overview of everything discovered.

In [15]:
print("=" * 70)
print("  SCHEMA DISCOVERY SUMMARY")
print("=" * 70)

print("\n--- DB2 (Production) ---")
print(f"Tables found: {len(all_db2)}")
for t, info in sorted(db2_schemas.items()):
    print(f"  {t:45s}  {info['n']:>8,} rows   cols: {sorted(info['cols'])}")

print(f"\n--- DB1 (Old Production) ---")
print(f"Tables found: {len(all_db1)}")
for t, info in sorted(db1_schemas.items()):
    print(f"  {t:45s}  {info['n']:>8,} rows   cols: {sorted(info['cols'])}")

print("\n" + "=" * 70)
print("SAVE THIS NOTEBOOK WITH OUTPUTS.")
print("Share back for final export query generation.")
print("=" * 70)

======================================================================
  SCHEMA DISCOVERY SUMMARY
======================================================================

--- DB2 (Production) ---
Tables found: 84
  core_address                                         23 rows   cols: ['address_line_1', 'address_line_2', 'address_type', 'city', 'content_type_id', 'country', 'created_at', 'id', 'object_id', 'state', 'updated_at', 'zip_code']
  core_business_event                                   0 rows   cols: ['actor_id', 'category_id', 'content_type_id', 'created_at', 'description', 'event_type', 'id', 'ip_address', 'level', 'metadata', 'object_id', 'target_user_id', 'user_agent']
  core_contact                                          0 rows   cols: ['contact_type', 'contact_value', 'content_type_id', 'created_at', 'id', 'is_primary', 'label', 'object_id', 'updated_at']
  core_customer_profile                                 0 rows   cols: ['created_at', 'customer_number', 'customer_since', 'email_opt_in', 'id', 'lifetime_spent', 'loyalty_tier', 'sms_opt_in', 'updated_at', 'user_id']
  core_employee_profile                                39 rows   cols: ['created_at', 'department_id', 'employee_number', 'employment_type', 'hire_date', 'id', 'manager_id', 'pay_grade_id', 'position', 'termination_date', 'updated_at', 'user_id']
  core_event_category                                   0 rows   cols: ['created_at', 'description', 'id', 'name', 'retention_days', 'updated_at']
  core_manifest                                         0 rows   cols: ['column_names', 'error_message', 'id', 'name', 'notes', 'processed', 'processed_at', 'row_count', 's3_file_id', 'type', 'uploaded_at', 'uploaded_by_id']
  core_s3_file                                         68 rows   cols: ['content_type', 'description', 'filename', 'id', 'is_public', 'key', 'metadata', 'size', 'uploaded_at', 'uploaded_by_id']
  core_user                                            39 rows   cols: ['birth_date', 'date_joined', 'email', 'emergency_contact_name', 'emergency_contact_phone', 'emergency_contact_relationship', 'first_name', 'id', 'is_active', 'is_customer', 'is_employee', 'is_staff', 'is_superuser', 'last_login', 'last_name', 'middle_name', 'password', 'phone', 'updated_at', 'username', 'work_location_id']
  core_user_groups                                     48 rows   cols: ['group_id', 'id', 'user_id']
  core_user_user_permissions                            0 rows   cols: ['id', 'permission_id', 'user_id']
  core_work_location                                    5 rows   cols: ['address_id', 'code', 'created_at', 'gradient_end', 'gradient_start', 'id', 'is_active', 'location_type', 'name', 'theme_color', 'updated_at']
  inventory_csv_field_mapping                         120 rows   cols: ['default_value', 'id', 'is_required', 'order', 'source_column', 'target_field', 'template_id', 'transform_expression']
  inventory_csv_template                               10 rows   cols: ['confidence_threshold', 'created_at', 'created_by_id', 'header_signature', 'id', 'is_active', 'name', 'updated_at', 'updated_by_id', 'vendor_id']
  inventory_customer_message                            3 rows   cols: ['click_url', 'created_at', 'end_date', 'id', 'is_active', 'message', 'priority', 'start_date', 'updated_at']
  inventory_item                                   59,833 rows   cols: ['bulk_id', 'bulk_quantity', 'created_at', 'disc_a', 'disc_b', 'id', 'inventory_purchase_order_id', 'last_printed_at', 'manifest_row_id', 'on_shelf_at', 'pricing_type', 'processing_completed_at', 'product_class_id', 'product_id', 'retail_amt', 'serial_number', 'sku', 'sku_print_count', 'sold_at', 'sold_for', 'starting_price', 'updated_at']
  inventory_item_history                           54,250 rows   cols: ['condition', 'destination_id', 'dispatch_to_id', 'id', 'item_id', 'location', 'notes', 'status', 'updated_by_id', 'updated_on']
  inventory_item_scan_history                     403,239 rows   cols: ['device_type', 'id', 'ip_address', 'item_id', 'scanned_at', 'session_id', 'user_agent']
  inventory_location                                   11 rows   cols: ['code', 'created_at', 'id', 'is_active', 'location_type', 'name', 'parent_id', 'updated_at']
  inventory_manifest_rows                          36,330 rows   cols: ['box_id', 'brand', 'category', 'created_at', 'description', 'id', 'model', 'pallet_id', 'purchase_order_id', 'quantity', 'retail_value', 'row_number', 'search_terms', 'sku', 'subcategory', 'upc', 'updated_at', 'vendor_sku']
  inventory_preprocessing_detail                   36,330 rows   cols: ['ai_generated_brand', 'ai_generated_model', 'ai_generated_title', 'ai_generation_status', 'bulk_quantity', 'created_at', 'disc_a', 'disc_b', 'id', 'is_bulk', 'item_generated_status', 'item_rows_generated_count', 'manifest_brand', 'manifest_description', 'manifest_match_status', 'manifest_model', 'manifest_quantity', 'manifest_retail_value', 'manifest_row_id', 'pricing_dynamics_status', 'pricing_type', 'product_match_status', 'purchase_order_id', 'row_number', 'selected_manifest_match_id', 'selected_product_match_id', 'starting_price', 'suggested_manifest_matches', 'suggested_product_matches', 'updated_at']
  inventory_pricing_template                            4 rows   cols: ['created_at', 'disc_a', 'disc_b', 'id', 'name', 'starting_price_pct', 'updated_at']
  inventory_processing_detail                      54,611 rows   cols: ['bulk_quantity', 'created_at', 'final_item_retail', 'final_price_disc_a', 'final_price_disc_b', 'final_price_starting', 'final_price_type', 'final_product_brand', 'final_product_id', 'final_product_model', 'final_product_title', 'history_status', 'id', 'init_item_retail', 'init_price_disc_a', 'init_price_disc_b', 'init_price_starting', 'init_price_type', 'init_product_brand', 'init_product_id', 'init_product_model', 'init_product_title', 'item_history_condition', 'item_history_destination_id', 'item_history_dispatch_to_id', 'item_history_id', 'item_history_location_id', 'item_history_notes', 'item_history_updated_at', 'item_history_updated_by', 'item_id', 'item_sku', 'manifest_brand', 'manifest_description', 'manifest_expected_qty', 'manifest_model', 'manifest_retail_value', 'manifest_row_id', 'manifest_row_number', 'manifest_search_terms', 'pricing_status', 'print_counter', 'processed_at', 'processed_by_id', 'product_items_cnt', 'product_po_items_cnt', 'product_search_terms', 'product_status', 'purchase_order_id', 'retail_status', 'search_terms', 'serial_number', 'status', 'updated_at']
  inventory_product                                41,509 rows   cols: ['ai_confidence', 'ai_suggested_title', 'brand', 'created_at', 'id', 'last_matched_at', 'match_count', 'model', 'product_class_id', 'title', 'updated_at']
  inventory_product_class                               0 rows   cols: ['class_description', 'class_name', 'created_at', 'id', 'is_active', 'updated_at']
  inventory_purchase_order                            103 rows   cols: ['condition', 'created_at', 'created_by_id', 'csv_template_id', 'description', 'expected_delivery', 'id', 'manifest_file_url', 'manifest_uploaded_at', 'notes', 'order_number', 'other_fees', 'preprocessing_completed_at', 'processing_completed_at', 'processing_started_at', 'purchase_date', 'purchase_price', 'quantity', 'raw_manifest_id', 'received_date', 'retail_value', 'rows_generated_at', 'shipping_cost', 'status', 'total_cost', 'updated_at', 'vendor_id']
  inventory_raw_manifest                               61 rows   cols: ['header_signature', 'id', 'name', 'row_count', 's3_file_id', 'uploaded_at', 'uploaded_by_id', 'vendor_id']
  inventory_standardization_run                        62 rows   cols: ['configuration', 'created_at', 'created_by_id', 'id', 'purchase_order_id', 'rows_created', 'template_used_id']
  inventory_store_configuration                         9 rows   cols: ['description', 'id', 'key', 'updated_at', 'updated_by_id', 'value']
  inventory_vendor                                      9 rows   cols: ['address_line1', 'address_line2', 'city', 'code', 'contact_name', 'created_at', 'created_by_id', 'email', 'id', 'name', 'phone', 'state', 'updated_at', 'vendor_type', 'website', 'zip_code']
  pos_bank_transaction                                 12 rows   cols: ['bank_confirmation_number', 'change_amount', 'created_at', 'deposit_amount', 'id', 'notes', 'performed_by_id', 'transaction_date', 'transaction_type', 'work_location_id']
  pos_cart                                         16,275 rows   cols: ['cashier_id', 'completed_at', 'created_at', 'credit_card_fee', 'customer_id', 'drawer_id', 'id', 'status', 'subtotal', 'tax_amount', 'tax_rate', 'total', 'updated_at']
  pos_cart_line                                    42,586 rows   cols: ['cart_id', 'created_at', 'discount_rule_id', 'id', 'item_id', 'line_total', 'product_brand', 'product_model', 'product_title', 'quantity', 'unit_price']
  pos_cash_deposit                                     13 rows   cols: ['amount', 'bank_transaction_id', 'created_at', 'created_by_id', 'denomination_count', 'deposit_date', 'id', 'notes', 'status', 'work_location_id']
  pos_cash_management_settings                          5 rows   cols: ['allow_force_close', 'auto_change_request_threshold', 'auto_create_next_drawer', 'auto_deposit_threshold', 'created_at', 'default_register_dimes', 'default_register_fifties', 'default_register_fives', 'default_register_hundreds', 'default_register_nickels', 'default_register_ones', 'default_register_pennies', 'default_register_quarters', 'default_register_tens', 'default_register_twenties', 'id', 'ideal_supplemental_dimes', 'ideal_supplemental_fifties', 'ideal_supplemental_fives', 'ideal_supplemental_hundreds', 'ideal_supplemental_nickels', 'ideal_supplemental_ones', 'ideal_supplemental_pennies', 'ideal_supplemental_quarters', 'ideal_supplemental_tens', 'ideal_supplemental_twenties', 'max_variance_without_approval', 'max_variance_without_explanation', 'min_deposit_amount', 'require_blind_count', 'require_dual_count', 'updated_at', 'updated_by_id', 'work_location_id']
  pos_change_request                                   13 rows   cols: ['bank_transaction_id', 'created_at', 'created_by_id', 'denomination_count', 'fulfilled_at', 'id', 'notes', 'request_date', 'status', 'total_amount', 'work_location_id']
  pos_discount_rule                                     2 rows   cols: ['button_text', 'created_at', 'created_by_id', 'description', 'discount_type', 'discount_value', 'end_date', 'id', 'is_active', 'min_purchase', 'name', 'start_date', 'updated_at']
  pos_drawer                                          229 rows   cols: ['cashier_id', 'closed_at', 'closing_cash', 'drawer_date', 'expected_cash', 'id', 'notes', 'opened_at', 'opening_cash', 'register_id']
  pos_drawer_shift                                    963 rows   cols: ['cash_breakdown', 'counted_cash', 'created_at', 'drawer_id', 'ended_at', 'expected_cash', 'id', 'new_cashier_id', 'previous_cashier_id', 'type', 'variance', 'variance_approved', 'variance_reason', 'verified_by_id']
  pos_payment                                      15,306 rows   cols: ['amount', 'amount_tendered', 'card_type', 'cart_id', 'change_given', 'id', 'payment_method', 'processed_at', 'reference_number']
  pos_receipt                                      15,306 rows   cols: ['cart_id', 'created_at', 'customer_declined', 'email_address', 'emailed', 'emailed_at', 'id', 'printed', 'printed_at', 'printer_name', 'receipt_number']
  pos_receipt_template                                  0 rows   cols: ['created_at', 'created_by_id', 'description', 'font_size', 'footer_text', 'header_text', 'id', 'include_barcode', 'include_qr_code', 'is_active', 'is_default', 'name', 'paper_width', 'return_policy_text', 'show_cashier_name', 'show_item_sku', 'show_logo', 'show_return_policy', 'store_address', 'store_phone', 'updated_at']
  pos_register                                          5 rows   cols: ['code', 'created_at', 'description', 'id', 'ideal_dimes', 'ideal_fifties', 'ideal_fives', 'ideal_hundreds', 'ideal_nickels', 'ideal_ones', 'ideal_pennies', 'ideal_quarters', 'ideal_tens', 'ideal_twenties', 'is_active', 'name', 'notes', 'work_location_id']
  pos_revenue_goal                                    182 rows   cols: ['created_at', 'created_by_id', 'date', 'goal_amount', 'id', 'notes', 'updated_at', 'work_location_id']
  pos_supplemental_drawer                               5 rows   cols: ['created_at', 'current_dimes', 'current_fifties', 'current_fives', 'current_hundreds', 'current_nickels', 'current_ones', 'current_pennies', 'current_quarters', 'current_tens', 'current_twenties', 'id', 'ideal_dimes', 'ideal_fifties', 'ideal_fives', 'ideal_hundreds', 'ideal_nickels', 'ideal_ones', 'ideal_pennies', 'ideal_quarters', 'ideal_tens', 'ideal_twenties', 'last_verified', 'updated_at', 'verified_by_id', 'work_location_id']
  pos_supplemental_drawer_transaction                  13 rows   cols: ['balance_after', 'cash_deposit_id', 'cash_in', 'cash_out', 'created_at', 'denomination_after', 'denomination_before', 'denomination_out', 'description', 'id', 'performed_by_id', 'related_drawer_id', 'transaction_date', 'transaction_type', 'work_location_id']
  pos_transaction_void                                  7 rows   cols: ['approved', 'approved_by_id', 'completed', 'completed_at', 'created_at', 'id', 'items_returned', 'manager_pin', 'new_cart_id', 'original_cart_id', 'reason', 'refund_amount', 'requested_by_id', 'void_type']

--- DB1 (Old Production) ---
Tables found: 58
  cart                                             53,304 rows   cols: ['close_time', 'code', 'drawer_cde', 'id', 'notes', 'open_time', 'replaced_cart_cde', 'sales_tax_percentage', 'subtotal_amt', 'tax_amt', 'thrift_plus_member_id', 'total_amt', 'total_discount_amt', 'total_payment_amt', 'total_taxable_amt', 'void', 'void_reason']
  cart_discount                                     1,505 rows   cols: ['cart_cde', 'cart_label', 'cart_value', 'discount_cde', 'id', 'taxable']
  cart_line                                       173,475 rows   cols: ['cart_cde', 'id', 'is_standard_bogo', 'item_cde', 'line_description', 'line_num', 'quantity', 'taxable', 'total_price_amt', 'unit_price_amt']
  department                                            8 rows   cols: ['id', 'manager_id', 'name']
  department_budget                                    36 rows   cols: ['budget_amt', 'budget_type_id', 'department_id', 'effective_date', 'end_date', 'id', 'notes', 'updated_by', 'updated_on']
  discount                                              3 rows   cols: ['code', 'discount_type', 'extra_data', 'id', 'is_combinable', 'label', 'product_codes', 'valid_from', 'valid_to', 'value_1', 'value_2', 'value_3', 'value_4']
  drawer                                              918 rows   cols: ['cashier_cde', 'close_cash_amt', 'close_manager_cde', 'close_time', 'code', 'id', 'open_cash_amt', 'open_manager_cde', 'open_time']
  employee_departments                                 33 rows   cols: ['department_id', 'employee_id']
  giftcard                                             31 rows   cols: ['balance', 'code', 'created_on', 'id', 'original_amount', 'status', 'updated_on']
  item                                            123,941 rows   cols: ['bulk_cde', 'code', 'id', 'is_static', 'line_number', 'order_number', 'price_lbl', 'product_cde', 'quantity', 'retail_amt', 'starting_price_amt']
  item_condition                                  130,112 rows   cols: ['as_of', 'condition_id', 'employee_cde', 'id', 'item_cde']
  item_destination                                130,108 rows   cols: ['as_of', 'department_id', 'employee_cde', 'id', 'item_cde', 'notes']
  item_dispatch                                    89,736 rows   cols: ['as_of', 'department_id', 'employee_cde', 'id', 'item_cde', 'notes']
  item_location                                         0 rows   cols: ['as_of', 'employee_cde', 'id', 'item_cde', 'location_id']
  item_status                                     217,305 rows   cols: ['as_of', 'employee_cde', 'id', 'item_cde', 'status_id']
  item_test_result                                      0 rows   cols: ['as_is_value', 'as_of', 'decision', 'id', 'item_cde', 'notes', 'repair_value', 'salvage_value']
  list_condition                                        7 rows   cols: ['condition_name', 'id']
  list_status                                          27 rows   cols: ['id', 'status_name']
  location                                              0 rows   cols: ['address_id', 'code', 'id', 'is_active', 'name', 'parent_location_id', 'type_id']
  manifest                                        107,748 rows   cols: ['brand', 'category', 'description', 'ext_retail_amt', 'id', 'line_number', 'model', 'order_number', 'pallet_id', 'product_cde', 'quantity', 'retail_amt', 'search_string_1', 'search_string_2', 'search_string_3', 'sku', 'subcategory', 'upc']
  payment                                          55,176 rows   cols: ['amount', 'cart_cde', 'fee_amount', 'giftcard_cde', 'id', 'pmt_string', 'type']
  price                                            10,816 rows   cols: ['amount', 'code', 'id', 'week_num', 'weeks_to_zero']
  price_index                                         234 rows   cols: ['amount', 'code', 'index', 'label']
  product                                         140,621 rows   cols: ['brand', 'code', 'id', 'model', 'title']
  product_attrs                                   152,983 rows   cols: ['attrs', 'category', 'id', 'last_instance', 'product_cde', 'quantity', 'retail_amt', 'subcategory', 'taxable', 'upc']
  purchase_order                                      210 rows   cols: ['condition_id', 'created_on', 'delivery_address_cde', 'description', 'fee_amt', 'id', 'number', 'paid_amt', 'paid_on', 'preprocessed_on', 'price_amt', 'processed_on', 'purchased_on', 'quantity', 'received_on', 'retail_amt', 'scheduled_delivery', 'shipping_amt']
  thrift_plus_payment                                   4 rows   cols: ['amount', 'cart_id', 'duration_months', 'end_date', 'id', 'member_id', 'payment_date', 'start_date']
  v_price_label                                       190 rows   cols: ['price_dynamic_lbl']

======================================================================
SAVE THIS NOTEBOOK WITH OUTPUTS.
Share back for final export query generation.
======================================================================

---
## Cleanup

In [16]:
eng2.dispose()
eng1.dispose()
print("Both engines disposed.")

Both engines disposed.